dataCallback([
  {"ko": "과학 기술", "en": "science and technology", "zh": "科学技术", "vi": "khoa học và công nghệ", "mn": "шинжлэх ухаан ба технологи", "ru": "наука и технологии"},
  {"ko": "어리석다", "en": "to be foolish", "zh": "愚蠢", "vi": "ngốc ngếch, khờ khạo", "mn": "тэнэг", "ru": "быть глупым"},
  {"ko": "책임지다", "en": "to take responsibility", "zh": "负责", "vi": "chịu trách nhiệm", "mn": "хариуцлага хүлээх", "ru": "нести ответственность"},
  {"ko": "뜻", "en": "translation", "zh": "翻译", "vi": "biên dịch", "mn": "орчуулга", "ru": "перевод"},
  {"ko": "유치원", "en": "kindergarten", "zh": "幼儿园", "vi": "trường mẫu giáo", "mn": "цэцэрлэг", "ru": "детский сад"},
  {"ko": "여전히", "en": "still", "zh": "仍然", "vi": "vẫn", "mn": "урьдын адил", "ru": "по-прежнему"},
  {"ko": "성산일출봉", "en": "Seongsan Ilchulbong (Sunrise Peak)", "zh": "城山日出峰", "vi": "Seongsan Ilchulbong", "mn": "Сонсан Илчулбон (Нар мандах оргил)", "ru": "Пик Сончан Ильчхульбон (место встречи рассвета на о. Чеджу)"},
  {"ko": "등록비", "en": "registration fee", "zh": "注册费", "vi": "phí đăng ký", "mn": "бүртгэлийн хураамж", "ru": "регистрационный сбор"},
  {"ko": "한턱내다", "en": "to treat", "zh": "请客", "vi": "chiêu đãi", "mn": "дайлах", "ru": "угощать"},
  {"ko": "선호하다", "en": "to prefer", "zh": "偏爱", "vi": "ưa thích", "mn": "илүүд үзэх", "ru": "предпочитать"},
  {"ko": "자막", "en": "subtitle", "zh": "字幕", "vi": "phụ đề", "mn": "хадмал орчуулга", "ru": "субтитры"},
  {"ko": "밤새도록", "en": "all night long", "zh": "通宵", "vi": "suốt đêm", "mn": "шөнөжин", "ru": "всю ночь напролёт"},
  {"ko": "집중력", "en": "concentration", "zh": "注意力", "vi": "sự tập trung", "mn": "төвлөрөл", "ru": "концентрация"},
  {"ko": "인스턴트", "en": "instant", "zh": "速食", "vi": "ăn liền", "mn": "түргэн", "ru": "растворимый (быстрого приготовления)"},
  {"ko": "양치질하다", "en": "to brush teeth", "zh": "刷牙", "vi": "đánh răng", "mn": "шүдээ угаах", "ru": "чистить зубы"},
  {"ko": "충치", "en": "cavity", "zh": "蛀牙", "vi": "sâu răng", "mn": "шүдний цоорол", "ru": "кариес 1-2    능력과 자질 Abilities & Qualities 한국어 표현 뜻 쪽"},
  {"ko": "이끌다", "en": "to lead", "zh": "引领", "vi": "dẫn dắt", "mn": "удирдан чиглүүлэх", "ru": "вести"},
  {"ko": "시도하다", "en": "to attempt", "zh": "尝试", "vi": "thử, thử nghiệm", "mn": "оролдох", "ru": "пытаться"},
  {"ko": "고려하다", "en": "to consider", "zh": "考虑", "vi": "cân nhắc", "mn": "харгалзан үзэх", "ru": "учитывать / принимать во внимание"},
  {"ko": "알려지다", "en": "to be known", "zh": "闻名", "vi": "được biết đến", "mn": "танигдах", "ru": "быть известным"},
  {"ko": "올림픽", "en": "Olympics", "zh": "奥运会", "vi": "Thế vận hội Olympic", "mn": "олимп", "ru": "Олимпийские игры"},
  {"ko": "종목", "en": "sports event", "zh": "项目", "vi": "danh mục", "mn": "спортын төрөл", "ru": "спортивная дисциплина"},
  {"ko": "금메달을 따다", "en": "to win a gold medal", "zh": "获得金牌", "vi": "giành huy chương vàng", "mn": "алтан медаль авах", "ru": "выиграть золотую медаль"},
  {"ko": "탄산음료", "en": "carbonated drink (soda)", "zh": "碳酸饮料", "vi": "đồ uống có ga", "mn": "хийжүүлсэн ундаа", "ru": "газированный напиток"},
  {"ko": "소매", "en": "sleeve", "zh": "袖子", "vi": "tay áo", "mn": "ханцуй", "ru": "рукав"},
  {"ko": "가리다", "en": "to cover", "zh": "遮住", "vi": "che", "mn": "хаах", "ru": "прикрывать"},
  {"ko": "개봉하다", "en": "to release", "zh": "上映", "vi": "công chiếu", "mn": "нээлтээ хийх", "ru": "выпускать (в прокат)"},
  {"ko": "시차", "en": "time difference", "zh": "时差", "vi": "chênh lệch múi giờ", "mn": "цагийн зөрүү", "ru": "разница во времени 서울대 한국어+ Workbook 4A 2  건강한 삶 Healthy Life 2-2    건강한 습관 Healthy Habits 한국어 표현 뜻 쪽"},
  {"ko": "표정", "en": "facial expression", "zh": "表情", "vi": "biểu cảm", "mn": "нүүрний хувирал", "ru": "выражение лица"},
  {"ko": "혈관", "en": "blood vessel", "zh": "血管", "vi": "mạch máu", "mn": "судас", "ru": "кровеносный сосуд"},
  {"ko": "질병", "en": "disease", "zh": "疾病", "vi": "bệnh tật", "mn": "өвчин", "ru": "болезнь"},
  {"ko": "호소하다", "en": "to appeal", "zh": "诉说", "vi": "kêu ca", "mn": "гомдоллох", "ru": "жаловаться"},
  {"ko": "수면 장애", "en": "sleep disorder", "zh": "睡眠障碍", "vi": "rối loạn giấc ngủ", "mn": "нойрны хямрал", "ru": "расстройство сна"},
  {"ko": "수선비", "en": "repair fee", "zh": "修理费", "vi": "phí sửa chữa", "mn": "засварын төлбөр", "ru": "плата за ремонт"},
  {"ko": "야근", "en": "working overtime", "zh": "加班", "vi": "làm thêm giờ", "mn": "илүү цагаар ажиллах", "ru": "сверхурочная работа 서울대 한국어+ Workbook 4A 3  선택과 변화 Choices & Changes 3-1    만족과 후회  Satisfaction & Regret 한국어 표현 뜻 쪽"},
  {"ko": "연속", "en": "consecutive", "zh": "连续", "vi": "liên tiếp", "mn": "дараалсан", "ru": "подряд"},
  {"ko": "수정", "en": "correction", "zh": "修改", "vi": "sự sửa chữa", "mn": "залруулга", "ru": "исправление"},
  {"ko": "상식", "en": "common sense", "zh": "常识", "vi": "kiến thức phổ thông", "mn": "нийтлэг мэдлэг", "ru": "здравый смысл"},
  {"ko": "풍부해지다", "en": "to be enriched", "zh": "变得丰富", "vi": "trở nên phong phú", "mn": "баяжих", "ru": "обогащаться 3-2    사회 변화 Social Change 한국어 표현 뜻 쪽"},
  {"ko": "정책", "en": "policy", "zh": "政策", "vi": "chính sách", "mn": "бодлого", "ru": "политика"},
  {"ko": "신뢰", "en": "trust", "zh": "信赖", "vi": "sự tin tưởng", "mn": "итгэл", "ru": "доверие"},
  {"ko": "기부하다", "en": "to donate", "zh": "捐赠", "vi": "quyên góp", "mn": "хандивлах", "ru": "жертвовать"},
  {"ko": "바람직하다", "en": "to be desirable", "zh": "可取", "vi": "lý tưởng, đúng đắn", "mn": "зүйтэй", "ru": "быть желательным"},
  {"ko": "참여하다", "en": "to participate", "zh": "参与", "vi": "tham gia", "mn": "оролцох", "ru": "участвовать"},
  {"ko": "국산", "en": "domestic", "zh": "国产", "vi": "hàng nội địa", "mn": "дотоодын", "ru": "отечественного производства"},
  {"ko": "헷갈리다", "en": "to be confused", "zh": "混淆", "vi": "bị nhầm lẫn", "mn": "эргэлзэх", "ru": "сбиваться с толку / запутаться"},
  {"ko": "혼동하다", "en": "to mix up", "zh": "混淆", "vi": "lẫn lộn", "mn": "андуурах", "ru": "путать / смешивать (понятия)"},
  {"ko": "부정하다", "en": "to deny", "zh": "否定", "vi": "phủ nhận", "mn": "үгүйсгэх", "ru": "отрицать"},
  {"ko": "불리다", "en": "to be called", "zh": "被称为", "vi": "được gọi là", "mn": "дуудагдах", "ru": "называться"},
  {"ko": "분야별", "en": "by sector", "zh": "按领域", "vi": "theo lĩnh vực", "mn": "салбар тус бүрээр", "ru": "по отраслям"},
  {"ko": "위로", "en": "comfort", "zh": "安慰", "vi": "an ủi", "mn": "тайтгарал", "ru": "утешение Review 1 한국어 표현 뜻 쪽"},
  {"ko": "증후군", "en": "syndrome", "zh": "综合征", "vi": "hội chứng", "mn": "хам шинж", "ru": "синдром"},
  {"ko": "여드름", "en": "acne", "zh": "青春痘", "vi": "mụn trứng cá", "mn": "батга", "ru": "прыщ"},
  {"ko": "전문직", "en": "profession", "zh": "专业职位", "vi": "nghề chuyên môn", "mn": "мэргэжлийн ажил", "ru": "профессия"},
  {"ko": "개발자", "en": "developer", "zh": "开发者", "vi": "nhà phát triển", "mn": "хөгжүүлэгч", "ru": "разработчик"},
  {"ko": "급여", "en": "salary", "zh": "工资", "vi": "lương", "mn": "цалин", "ru": "зарплата"},
  {"ko": "곡물", "en": "grain", "zh": "谷物", "vi": "ngũ cốc", "mn": "үр тариа", "ru": "зерновые"},
  {"ko": "제사를 지내다", "en": "to perform ancestral rites", "zh": "祭祀", "vi": "cúng giỗ", "mn": "тахилга хийх", "ru": "проводить поминальный обряд"},
  {"ko": "필수", "en": "a must", "zh": "必需", "vi": "thiết yếu", "mn": "зайлшгүй", "ru": "необходимость"},
  {"ko": "재혼", "en": "remarriage", "zh": "再婚", "vi": "tái hôn", "mn": "дахин гэрлэлт", "ru": "повторный брак"},
  {"ko": "손목", "en": "wrist", "zh": "手腕", "vi": "cổ tay", "mn": "бугуй", "ru": "запястье"},
  {"ko": "손목 터널 증후군", "en": "carpal tunnel syndrome", "zh": "腕管综合征", "vi": "hội chứng ống cổ tay", "mn": "бугуйн сувгийн хам шинж", "ru": "синдром запястного канала"},
  {"ko": "소방관", "en": "firefighter", "zh": "消防员", "vi": "lính cứu hỏa", "mn": "гал сөнөөгч", "ru": "пожарный"},
  {"ko": "출동하다", "en": "to go into action", "zh": "出动", "vi": "xuất quân", "mn": "үүрэг гүйцэтгэхээр явах", "ru": "выезжать (на вызов)"},
  {"ko": "백신", "en": "vaccine", "zh": "疫苗", "vi": "vắc-xin", "mn": "вакцин", "ru": "вакцина"},
  {"ko": "명단", "en": "list", "zh": "名单", "vi": "danh sách", "mn": "нэрсийн жагсаалт", "ru": "список"},
  {"ko": "각설탕", "en": "sugar cube", "zh": "方糖", "vi": "đường viên", "mn": "дөрвөлжин саахар", "ru": "кусковой сахар 서울대 한국어+ Workbook 4A 4  기후와 문화 Climate & Culture 4-1    날씨와 기후  Weather & Climate 한국어 표현 뜻 쪽"},
  {"ko": "묵다", "en": "to stay", "zh": "住宿", "vi": "ở lại", "mn": "хоноглох", "ru": "ночевать"},
  {"ko": "1인 가구", "en": "single-person household", "zh": "单人家庭", "vi": "hộ gia đình một người", "mn": "нэг гишүүнтэй өрх", "ru": "домохозяйство из одного человека"},
  {"ko": "피해를 입다", "en": "to suffer damage", "zh": "遭受损失", "vi": "chịu thiệt hại", "mn": "хохирол амсах", "ru": "понести ущерб 4-2    기후와 문화의 특징 Climate & Characteristics of Culture 한국어 표현 뜻 쪽"},
  {"ko": "집중적으로", "en": "intensively", "zh": "集中地", "vi": "một cách tập trung", "mn": "төвлөрсөн байдлаар", "ru": "интенсивно"},
  {"ko": "곰팡이", "en": "mold", "zh": "霉菌", "vi": "nấm mốc", "mn": "хөгц", "ru": "плесень"},
  {"ko": "특산품", "en": "regional product", "zh": "特产", "vi": "đặc sản", "mn": "онцлог бүтээгдэхүүн", "ru": "местный продукт"},
  {"ko": "기술품", "en": "tech product", "zh": "技术产品", "vi": "sản phẩm công nghệ", "mn": "технологийн бүтээгдэхүүн", "ru": "техническое изделие 서울대 한국어+ Workbook 4A 5  여행의 즐거움 Delight of Travel 4-3    아름다운 풍경 Beautiful Scenery 한국어 표현 뜻 쪽"},
  {"ko": "일몰", "en": "sunset", "zh": "日落", "vi": "hoàng hôn", "mn": "нар жаргах", "ru": "закат"},
  {"ko": "시들다", "en": "to wilt", "zh": "枯萎", "vi": "héo", "mn": "хатах", "ru": "увядать"},
  {"ko": "그늘", "en": "shade", "zh": "阴凉处", "vi": "bóng râm", "mn": "сүүдэр", "ru": "тень 4-4    여행의 기쁨 Joy of Travel 한국어 표현 뜻 쪽"},
  {"ko": "일출", "en": "sunrise", "zh": "日出", "vi": "bình minh", "mn": "нар мандах", "ru": "восход солнца 서울대 한국어+ Workbook 4A 6  공연과 축제 Performances & Festivals 6-1    함께 즐기는 축제  Enjoying the Festival Together 한국어 표현 뜻 쪽"},
  {"ko": "공유", "en": "sharing", "zh": "分享", "vi": "chia sẻ", "mn": "хуваалцах", "ru": "совместное использование"},
  {"ko": "마침", "en": "just so happened to be", "zh": "正好", "vi": "vừa hay", "mn": "яг", "ru": "как раз"},
  {"ko": "인상에 남다", "en": "to be impressive", "zh": "留下印象", "vi": "để lại ấn tượng", "mn": "сэтгэгдэл үлдэх", "ru": "остаться в памяти"},
  {"ko": "상품권", "en": "gift certificate", "zh": "商品券", "vi": "phiếu quà tặng", "mn": "бэлгийн карт", "ru": "подарочный сертификат"},
  {"ko": "취향", "en": "preference", "zh": "取向", "vi": "sở thích", "mn": "сонирхол", "ru": "предпочтение"},
  {"ko": "충전기", "en": "charger", "zh": "充电器", "vi": "sạc pin", "mn": "цэнэглэгч", "ru": "зарядное устройство 6-2    감상과 평가  Reviews & Evaluations 한국어 표현 뜻 쪽"},
  {"ko": "도저히", "en": "cannot possibly", "zh": "无论如何也", "vi": "cho dù thế nào", "mn": "хэзээ ч", "ru": "никак не"},
  {"ko": "요인", "en": "key factor", "zh": "因素", "vi": "yếu tố", "mn": "хүчин зүйл", "ru": "фактор"},
  {"ko": "심사위원", "en": "judge", "zh": "评委", "vi": "giám khảo", "mn": "шүүгч", "ru": "член жюри"},
  {"ko": "만점", "en": "perfect score", "zh": "满分", "vi": "điểm tối đa", "mn": "дээд оноо", "ru": "высший балл"},
  {"ko": "(날씨가) 궂다", "en": "(weather) to be bad", "zh": "(天气)恶劣", "vi": "(thời tiết) xấu", "mn": "(цаг агаар) муу", "ru": "(погода) плохая"},
  {"ko": "결말", "en": "ending", "zh": "结局", "vi": "kết thúc", "mn": "төгсгөл", "ru": "концовка"},
  {"ko": "소품", "en": "prop", "zh": "道具", "vi": "đạo cụ", "mn": "тайзны хэрэглэл", "ru": "реквизит"},
  {"ko": "통행", "en": "transit", "zh": "通行", "vi": "lưu thông", "mn": "зорчих", "ru": "проезд"},
  {"ko": "노숙자", "en": "homeless person", "zh": "流浪汉", "vi": "người vô gia cư", "mn": "орон гэргүй хүн", "ru": "бездомный"},
  {"ko": "재산", "en": "fortune", "zh": "财产", "vi": "tài sản", "mn": "хөрөнгө", "ru": "имущество Review 2 한국어 표현 뜻 쪽"},
  {"ko": "편집", "en": "editing", "zh": "编辑", "vi": "biên tập", "mn": "эдитлэх", "ru": "редактирование"},
  {"ko": "책자", "en": "brochure", "zh": "小册子", "vi": "cuốn sách", "mn": "товхимол", "ru": "брошюра"},
  {"ko": "열대 과일", "en": "tropical fruit", "zh": "热带水果", "vi": "trái cây nhiệt đới", "mn": "халуун орны жимс", "ru": "тропический фрукт"},
  {"ko": "탈춤", "en": "mask dance", "zh": "假面舞", "vi": "múa mặt nạ", "mn": "багт наадам", "ru": "танец в масках"},
  {"ko": "머드", "en": "mud", "zh": "泥浆", "vi": "bùn", "mn": "шавар", "ru": "грязь"},
  {"ko": "방식", "en": "method", "zh": "方式", "vi": "phương thức", "mn": "арга", "ru": "метод"},
  {"ko": "특산물", "en": "regional specialties", "zh": "特产", "vi": "đặc sản", "mn": "орон нутгийн онцлог бүтээгдэхүүн", "ru": "местные продукты"},
  {"ko": "대형", "en": "large", "zh": "大型", "vi": "cỡ lớn", "mn": "том", "ru": "крупный"},
  {"ko": "해상", "en": "maritime", "zh": "海上", "vi": "trên biển", "mn": "далайн", "ru": "морской"},
  {"ko": "담을 쌓다", "en": "to build a wall", "zh": "筑墙", "vi": "xây tường", "mn": "хана хэрэм босгох", "ru": "(досл.) построить стену / отстраниться"},
  {"ko": "지붕", "en": "roof", "zh": "屋顶", "vi": "mái nhà", "mn": "дээвэр", "ru": "крыша"},
  {"ko": "새끼줄", "en": "straw rope", "zh": "草绳", "vi": "dây rơm", "mn": "сүрлэн олс", "ru": "соломенная верёвка"},
  {"ko": "무음", "en": "silent", "zh": "静音", "vi": "im lặng", "mn": "чимээгүй", "ru": "беззвучный"},
  {"ko": "체온", "en": "body temperature", "zh": "体温", "vi": "nhiệt độ cơ thể", "mn": "биеийн температур", "ru": "температура тела"},
  {"ko": "일사병", "en": "heatstroke", "zh": "中暑", "vi": "bệnh say nắng, bệnh cảm nắng", "mn": "наршилт", "ru": "солнечный удар"},
  {"ko": "현지", "en": "local", "zh": "当地", "vi": "địa phương", "mn": "орон нутгийн", "ru": "местный"},
  {"ko": "선진국", "en": "developed country", "zh": "发达国家", "vi": "nước phát triển", "mn": "хөгжингүй орон", "ru": "развитая страна"},
  {"ko": "다국적", "en": "multinational", "zh": "跨国", "vi": "đa quốc gia", "mn": "олон үндэстний", "ru": "многонациональный"},
  {"ko": "특색", "en": "distinct feature", "zh": "特色", "vi": "đặc sắc", "mn": "онцлог", "ru": "особенность"},
  {"ko": "가라앉다", "en": "to be down", "zh": "消沉", "vi": "chìm xuống, lắng xuống", "mn": "буурах", "ru": "опускаться (о настроении)"},
  {"ko": "지형", "en": "geography", "zh": "地形", "vi": "địa hình", "mn": "газрын гадарга", "ru": "рельеф"},
  {"ko": "판소리", "en": "Korean folk opera", "zh": "板索里", "vi": "pansori", "mn": "паны чимээ", "ru": "пхансори (традиционное корейское пение-рассказ)"},
  {"ko": "동창회", "en": "class reunion", "zh": "同学会", "vi": "hội đồng môn", "mn": "төгсөгчдийн уулзалт", "ru": "встреча выпускников 서울대 한국어+ Workbook 4A 7  숫자로 보는 세상 World in Numbers 7-1    조사 결과  Survey Results 한국어 표현 뜻 쪽"},
  {"ko": "민감해지다", "en": "to become sensitive", "zh": "变得敏感", "vi": "trở nên nhạy cảm", "mn": "мэдрэмтгий болох", "ru": "становиться чувствительным"},
  {"ko": "잠자리", "en": "dragonfly", "zh": "蜻蜓", "vi": "con chuồn chuồn", "mn": "соно", "ru": "стрекоза"},
  {"ko": "곤충", "en": "insect", "zh": "昆虫", "vi": "côn trùng", "mn": "шавж", "ru": "насекомое"},
  {"ko": "냉동", "en": "frozen", "zh": "冷冻", "vi": "đông lạnh", "mn": "хөлдөөсөн", "ru": "замороженный"},
  {"ko": "생고기", "en": "raw meat", "zh": "生肉", "vi": "thịt sống", "mn": "түүхий мах", "ru": "сырое мясо"},
  {"ko": "되도록", "en": "if possible", "zh": "尽量", "vi": "nếu có thể", "mn": "аль болох", "ru": "по возможности"},
  {"ko": "아무래도", "en": "by any possibility", "zh": "不管怎样", "vi": "dù sao đi nữa", "mn": "ямартай ч", "ru": "в любом случае"},
  {"ko": "회계사", "en": "accountant", "zh": "会计师", "vi": "kế toán viên", "mn": "нягтлан бодогч", "ru": "бухгалтер"},
  {"ko": "청첩장", "en": "wedding invitation", "zh": "请柬", "vi": "thiệp cưới", "mn": "хуримын урилга", "ru": "свадебное приглашение"},
  {"ko": "피로 회복", "en": "fatigue recovery", "zh": "恢复疲劳", "vi": "phục hồi cơ thể", "mn": "ядаргаа тайлах", "ru": "восстановление от усталости"},
  {"ko": "여가 시간", "en": "spare time", "zh": "闲暇时间", "vi": "thời gian rảnh", "mn": "чөлөөт цаг", "ru": "свободное время"},
  {"ko": "칼슘", "en": "calcium", "zh": "钙", "vi": "canxi", "mn": "кальци", "ru": "кальций"},
  {"ko": "튼튼하다", "en": "to be strong", "zh": "结实", "vi": "chắc chắn", "mn": "бат бөх", "ru": "быть крепким 7-2    통계와 그래프  Statistics & Graphs 한국어 표현 뜻 쪽"},
  {"ko": "허리둘레", "en": "waist size", "zh": "腰围", "vi": "vòng eo", "mn": "бүсэлхийн тойрог", "ru": "обхват талии"},
  {"ko": "유산소", "en": "cardio", "zh": "有氧（运动）", "vi": "tập thể dục nhịp điệu", "mn": "аэробик", "ru": "аэробный"},
  {"ko": "해열제", "en": "antipyretic (drug)", "zh": "退烧药", "vi": "thuốc hạ sốt", "mn": "халуун бууруулах эм", "ru": "жаропонижающее"},
  {"ko": "꾸미다", "en": "to decorate", "zh": "装饰", "vi": "trang trí", "mn": "чимэглэх", "ru": "украшать"},
  {"ko": "경쟁이 치열하다", "en": "competition is fierce", "zh": "竞争激烈", "vi": "cạnh tranh khốc liệt", "mn": "өрсөлдөөн ширүүн", "ru": "конкуренция ожесточённая"},
  {"ko": "우주", "en": "space", "zh": "宇宙", "vi": "vũ trụ", "mn": "сансар огторгуй", "ru": "космос"},
  {"ko": "생명체", "en": "organism", "zh": "生命体", "vi": "sinh vật", "mn": "амьд биет", "ru": "живой организм"},
  {"ko": "투표", "en": "vote", "zh": "投票", "vi": "bỏ phiếu", "mn": "санал хураалт", "ru": "голосование"},
  {"ko": "현상", "en": "phenomena", "zh": "现象", "vi": "hiện tượng", "mn": "үзэгдэл", "ru": "явление"},
  {"ko": "대중", "en": "public", "zh": "大众", "vi": "công chúng", "mn": "олон нийт", "ru": "публика"},
  {"ko": "수집하다", "en": "to collect", "zh": "收集", "vi": "sưu tầm", "mn": "цуглуулах", "ru": "собирать, коллекционировать"},
  {"ko": "사고력", "en": "thinking skills", "zh": "思考力", "vi": "năng lực tư duy", "mn": "сэтгэн бодох чадвар", "ru": "мыслительные способности 서울대 한국어+ Workbook 4A 8  대중문화 Pop Culture 8-1    스타와 대중문화  Stars & Pop Culture 한국어 표현 뜻 쪽"},
  {"ko": "남몰래", "en": "secretly", "zh": "暗中", "vi": "một cách lén lút, một cách bí mật", "mn": "нууцаар", "ru": "тайно"},
  {"ko": "자상하다", "en": "to be thoughtful", "zh": "体贴", "vi": "rành rọt, cụ thể, tận tụy", "mn": "халамжтай", "ru": "заботливый"},
  {"ko": "무패", "en": "undefeated", "zh": "不败", "vi": "không thất bại, không thua", "mn": "ялагчгүй", "ru": "без поражений"},
  {"ko": "사기꾼", "en": "con artist", "zh": "骗子", "vi": "kẻ lừa đảo", "mn": "залилагч", "ru": "мошенник 8-2    대중문화의 영향  Pop Culture Influence 한국어 표현 뜻 쪽"},
  {"ko": "창작자", "en": "creator", "zh": "创作者", "vi": "người sáng tạo", "mn": "бүтээгч", "ru": "автор, создатель"},
  {"ko": "개선하다", "en": "to improve", "zh": "改善", "vi": "cải thiện", "mn": "сайжруулах", "ru": "улучшать"},
  {"ko": "댓글을 달다", "en": "to leave a comment", "zh": "发表评论", "vi": "để lại bình luận", "mn": "сэтгэгдэл үлдээх", "ru": "оставлять комментарий"},
  {"ko": "국회 의원 선거", "en": "parliamentary election", "zh": "国会议员选举", "vi": "bầu cử quốc hội", "mn": "парламентын сонгууль", "ru": "парламентские выборы"},
  {"ko": "책임을 묻다", "en": "to hold somebody accountable", "zh": "追究责任", "vi": "truy cứu trách nhiệm", "mn": "хариуцлага тооцох", "ru": "привлекать к ответственности"},
  {"ko": "따지다", "en": "to determine", "zh": "计较", "vi": "truy hỏi, bắt bẻ", "mn": "тодруулах", "ru": "выяснять 서울대 한국어+ Workbook 4A 9  스포츠의 세계 World of Sports 9-1    흥미진진한 경기  Exciting Matches 한국어 표현 뜻 쪽"},
  {"ko": "승부차기", "en": "penalty shoot-out", "zh": "点球大战", "vi": "sút luân lưu", "mn": "торгуулийн цохилт", "ru": "серия пенальти"},
  {"ko": "바둑", "en": "(the game of) go", "zh": "围棋", "vi": "cờ vây", "mn": "гоо даам", "ru": "го (игра)"},
  {"ko": "비상벨", "en": "emergency bell", "zh": "紧急铃", "vi": "chuông báo động", "mn": "онцгой байдлын хонх", "ru": "аварийный звонок"},
  {"ko": "이리저리", "en": "here and there", "zh": "到处", "vi": "đây đó", "mn": "энд тэнд", "ru": "туда-сюда"},
  {"ko": "선서하다", "en": "to take an oath", "zh": "宣誓", "vi": "tuyên thệ", "mn": "тангараг өргөх", "ru": "приносить присягу"},
  {"ko": "놀이터", "en": "playground", "zh": "游乐场", "vi": "sân chơi", "mn": "тоглоомын талбай", "ru": "игровая площадка"},
  {"ko": "바퀴", "en": "lap", "zh": "圈", "vi": "bánh xe", "mn": "тойрог", "ru": "круг"},
  {"ko": "쭉 내밀다", "en": "to stretch out", "zh": "伸出", "vi": "duỗi ra, duỗi thẳng", "mn": "сунгаж гаргах", "ru": "вытягивать 9-2    경기와 규칙  Matches & Rules 한국어 표현 뜻 쪽"},
  {"ko": "거주하다", "en": "to reside", "zh": "居住", "vi": "cư trú", "mn": "оршин суух", "ru": "проживать"},
  {"ko": "반죽", "en": "dough", "zh": "面团", "vi": "bột nhào", "mn": "зуурсан гурил", "ru": "тесто"},
  {"ko": "전라북도", "en": "Jeollabuk-do", "zh": "全罗北道", "vi": "tỉnh Jeollabuk", "mn": "Чоллабүк аймаг", "ru": "Провинция Чолла-Пукто"},
  {"ko": "명창", "en": "master singer", "zh": "名唱", "vi": "danh ca (người hay hát các bài hát truyền thống)", "mn": "алдарт дуучин", "ru": "мастер исполнения пхансори"},
  {"ko": "소속되다", "en": "to belong to", "zh": "属于", "vi": "được thuộc về, được trực thuộc", "mn": "харьяалагдах", "ru": "принадлежать к группе, быть приписанным"},
  {"ko": "재택근무", "en": "work from home (WFH)", "zh": "居家办公", "vi": "làm việc tại nhà", "mn": "гэрээсээ ажиллах", "ru": "работа на дому"},
  {"ko": "협조", "en": "cooperation", "zh": "协助", "vi": "hợp tác", "mn": "хамтын ажиллагаа", "ru": "сотрудничество"},
  {"ko": "가솔린 차", "en": "gas(oline) car", "zh": "汽油车", "vi": "xe chạy xăng", "mn": "бензин машин", "ru": "бензиновый автомобиль"},
  {"ko": "전기 차", "en": "electric car", "zh": "电动汽车", "vi": "xe điện", "mn": "цахилгаан машин", "ru": "электромобиль"},
  {"ko": "인구", "en": "population", "zh": "人口", "vi": "dân số", "mn": "хүн ам", "ru": "население"},
  {"ko": "수입량", "en": "import volume", "zh": "进口量", "vi": "lượng nhập khẩu", "mn": "импортын хэмжээ", "ru": "объём импорта"},
  {"ko": "역무원", "en": "station employee", "zh": "站务员", "vi": "nhân viên nhà ga", "mn": "өртөөний ажилтан", "ru": "работник станции"},
  {"ko": "일회용", "en": "single-use", "zh": "一次性", "vi": "dùng một lần", "mn": "нэг удаагийн", "ru": "одноразовый"},
  {"ko": "권유", "en": "suggestion", "zh": "建议", "vi": "sự khuyên nhủ, sự khuyên bảo", "mn": "зөвлөмж", "ru": "предложение / совет (с побуждением)"},
  {"ko": "선수권 대회", "en": "championship", "zh": "锦标赛", "vi": "giải vô địch", "mn": "аварга шалгаруулах тэмцээн", "ru": "чемпионат"},
  {"ko": "체급", "en": "weight class", "zh": "重量级", "vi": "hạng cân", "mn": "жингийн ангилал", "ru": "весовая категория"},
  {"ko": "치러지다", "en": "to take place", "zh": "举行", "vi": "được tổ chức", "mn": "зохион байгуулагдах", "ru": "проводиться (о мероприятии, экзамене, соревновании)"},
  {"ko": "인상률", "en": "increase rate", "zh": "上调率", "vi": "tỷ lệ tăng", "mn": "нэмэгдлийн хувь", "ru": "процент повышения"},
  {"ko": "대책", "en": "measures", "zh": "对策", "vi": "đối sách", "mn": "арга хэмжээ", "ru": "меры"},
  {"ko": "이삿짐 업체", "en": "moving company", "zh": "搬家公司", "vi": "công ty chuyển nhà", "mn": "нүүлгэлтийн компани", "ru": "транспортная компания по переезду, перевозке вещей"},
  {"ko": "떠올리다", "en": "to think of", "zh": "想起", "vi": "nhớ đến, chợt nhớ ra, hiện lên", "mn": "санах", "ru": "вспоминать"},
  {"ko": "추첨", "en": "draw", "zh": "抽签", "vi": "sự rút thăm", "mn": "сугалаа", "ru": "жеребьёвка"},
  {"ko": "나눔", "en": "sharing", "zh": "分享", "vi": "sự chia sẻ", "mn": "хуваалцах", "ru": "разделение"},
  {"ko": "번거롭다", "en": "to be cumbersome", "zh": "麻烦", "vi": "phiền phức", "mn": "төвөгтэй", "ru": "быть обременительным"},
  {"ko": "교류하다", "en": "to engage", "zh": "交流", "vi": "giao lưu", "mn": "солилцох", "ru": "обмениваться"},
  {"ko": "안팎", "en": "inside and outside", "zh": "内外", "vi": "trong ngoài", "mn": "дотор гадна", "ru": "внутри и снаружи"},
  {"ko": "인성", "en": "character", "zh": "人性", "vi": "nhân cách, nhân tính", "mn": "хүн чанар", "ru": "характер"},
  {"ko": "무능력하다", "en": "to be incompetent", "zh": "无能", "vi": "bất tài", "mn": "чадваргүй", "ru": "быть некомпетентным"},
  {"ko": "액수", "en": "amount", "zh": "数额", "vi": "số tiền", "mn": "мөнгөн дүн", "ru": "сумма"},
  {"ko": "출산율", "en": "birth rate", "zh": "生育率", "vi": "tỷ lệ sinh", "mn": "төрөлтийн түвшин", "ru": "уровень рождаемости"},
  {"ko": "진로를 정하다", "en": "to determine one’s career", "zh": "决定前途", "vi": "định hướng nghề nghiệp", "mn": "мэргэжлээ сонгох", "ru": "определиться с карьерой"},
  {"ko": "진로를 고민하다", "en": "to worry about one’s career", "zh": "为前途烦恼", "vi": "trăn trở về con đường tương lai", "mn": "ирээдүйнхээ талаар санаа зовох", "ru": "беспокоиться о карьере"},
  {"ko": "진로를 바꾸다", "en": "to change one’s career", "zh": "改变方向", "vi": "thay đổi con đường sự nghiệp", "mn": "замаа өөрчлөх", "ru": "сменить направление карьеры"},
  {"ko": "창업하다", "en": "to start a business", "zh": "创业", "vi": "khởi nghiệp", "mn": "бизнес эхлүүлэх", "ru": "начинать бизнес"},
  {"ko": "대학원에 진학하다", "en": "to enter graduate school", "zh": "上研究生院", "vi": "học lên cao học", "mn": "магистрантурт элсэх", "ru": "поступать в магистратуру"},
  {"ko": "취업하다", "en": "to get a job", "zh": "就业", "vi": "tìm việc", "mn": "ажилд орох", "ru": "устроиться на работу"},
  {"ko": "소질이 있다 / 없다", "en": "to have talent / to not have talent", "zh": "有 / 没有天分", "vi": "có / không có năng khiếu", "mn": "авьяастай / авьяасгүй", "ru": "иметь / не иметь талант"},
  {"ko": "전공을 살리다", "en": "to make the most of one’s major", "zh": "专业对口", "vi": "phát huy chuyên ngành", "mn": "мэргэжлээ ашиглах", "ru": "работать по специальности"},
  {"ko": "적성에 맞다 / 안 맞다", "en": "to match one’s aptitude / to not match one’s aptitude", "zh": "符合 / 不符合天性", "vi": "phù hợp / không phù hợp với năng lực bản thân", "mn": "сонирхолд нийцэх / нийцэхгүй", "ru": "подходить / не подходить по призванию"},
  {"ko": "전망이 밝다 / 어둡다", "en": "future is bright / dark", "zh": "前景光明 / 暗淡", "vi": "tương lai tương sáng / mờ mịt", "mn": "ирээдүй гэрэлтэй / бүдэг", "ru": "светлое / тёмное будущее"},
  {"ko": "생활비", "en": "living expenses", "zh": "生活费", "vi": "phí sinh hoạt", "mn": "амьжиргааны зардал", "ru": "расходы на жизнь"},
  {"ko": "분야", "en": "area", "zh": "领域", "vi": "lĩnh vực", "mn": "салбар", "ru": "область"},
  {"ko": "디자인과", "en": "Design Department", "zh": "设计系", "vi": "khoa thiết kế", "mn": "дизайны тэнхим", "ru": "факультет дизайна"},
  {"ko": "작업하다", "en": "to work", "zh": "工作", "vi": "làm việc", "mn": "ажиллах", "ru": "работать"},
  {"ko": "시식", "en": "food sampling", "zh": "品尝", "vi": "ăn thử", "mn": "амталгаа", "ru": "дегустация"},
  {"ko": "관련되다", "en": "to be related", "zh": "有关", "vi": "có liên quan", "mn": "холбоотой байх", "ru": "быть связанным"},
  {"ko": "그다지", "en": "not as much", "zh": "不太", "vi": "không... lắm", "mn": "төдийлөн", "ru": "не так уж"},
  {"ko": "경험을 쌓다", "en": "to gain experience", "zh": "积累经验", "vi": "tích lũy kinh nghiệm", "mn": "туршлага хуримтлуулах", "ru": "набираться опыта"},
  {"ko": "훈련사", "en": "trainer", "zh": "训练师", "vi": "huấn luyện viên", "mn": "сургагч", "ru": "дрессировщик"},
  {"ko": "훈련시키다", "en": "to train", "zh": "训练", "vi": "huấn luyện, đào tạo", "mn": "сургах", "ru": "дрессировать"},
  {"ko": "받아들이다", "en": "to accept", "zh": "接受", "vi": "tiếp nhận, tiếp thu, chấp nhận", "mn": "хүлээн авах", "ru": "принимать"},
  {"ko": "자질", "en": "quality", "zh": "资质", "vi": "tố chất", "mn": "ур чадвар", "ru": "способности, задатки, качество"},
  {"ko": "휴일", "en": "day off", "zh": "假日", "vi": "ngày nghỉ", "mn": "амралтын өдөр", "ru": "выходной день"},
  {"ko": "불규칙하다", "en": "to be irregular", "zh": "不规律", "vi": "không đều đặn", "mn": "тогтмол бус", "ru": "нерегулярный 1-2    능력과 자질 Abilities & Qualities 한국어 표현 뜻 쪽"},
  {"ko": "공감 능력이 뛰어나다", "en": "to have extraordinary empathy", "zh": "共情能力强", "vi": "có khả năng đồng cảm tốt", "mn": "бусдыг ойлгох чадвар сайтай", "ru": "обладать высоким уровнем эмпатии"},
  {"ko": "리더십이 있다", "en": "to have leadership", "zh": "有领导能力", "vi": "có năng lực lãnh đạo", "mn": "манлайлах чадвартай", "ru": "иметь лидерские качества"},
  {"ko": "설득력이있다", "en": "to be persuasive", "zh": "有说服力", "vi": "có sức thuyết phục", "mn": "ятгах чадвартай", "ru": "быть убедительным"},
  {"ko": "유머 감각이 있다", "en": "to have a sense of humor", "zh": "有幽默感", "vi": "có khiếu hài hước", "mn": "хошин шогийн мэдрэмжтэй", "ru": "иметь чувство юмора"},
  {"ko": "책임감이 강하다", "en": "to have a strong sense of responsibility", "zh": "责任心强", "vi": "có tinh thần trách nhiệm cao", "mn": "хариуцлагатай", "ru": "иметь сильное чувство ответственности"},
  {"ko": "긍정적", "en": "positive", "zh": "积极", "vi": "tích cực", "mn": "эерэг", "ru": "позитивный"},
  {"ko": "도전적", "en": "to be challenging", "zh": "有挑战性的", "vi": "tính thử thách", "mn": "сорилттой", "ru": "амбициозный, представлять собой вызов"},
  {"ko": "사교적", "en": "sociable", "zh": "社交的", "vi": "hòa đồng", "mn": "нийтэч", "ru": "общительный"},
  {"ko": "적극적", "en": "active", "zh": "积极", "vi": "tích cực", "mn": "идэвхтэй", "ru": "активный"},
  {"ko": "창의적", "en": "creative", "zh": "有创意的", "vi": "sáng tạo", "mn": "бүтээлч", "ru": "творческий"},
  {"ko": "특성", "en": "characteristics", "zh": "特性", "vi": "đặc tính", "mn": "онцлог", "ru": "характеристика"},
  {"ko": "장점", "en": "strength", "zh": "优点", "vi": "ưu điểm", "mn": "давуу тал", "ru": "сильная сторона"},
  {"ko": "또한", "en": "also", "zh": "而且", "vi": "ngoài ra", "mn": "мөн", "ru": "также"},
  {"ko": "인재상", "en": "type of talent", "zh": "人才观", "vi": "hình mẫu nhân tài lý tưởng", "mn": "хүсдэг хүний дүр төрх", "ru": "идеальный кандидат, желаемый тип специалиста"},
  {"ko": "배려하다", "en": "to be considerate", "zh": "关怀", "vi": "quan tâm", "mn": "хүндэтгэх", "ru": "заботиться, учитывать чувства других"},
  {"ko": "어우러지다", "en": "to get along", "zh": "融合", "vi": "hòa hợp", "mn": "зохицох", "ru": "гармонично сочетаться, сливаться"},
  {"ko": "소통하다", "en": "to communicate", "zh": "沟通", "vi": "giao tiếp", "mn": "харилцах", "ru": "общаться"},
  {"ko": "효과적", "en": "effective", "zh": "有效", "vi": "hiệu quả", "mn": "үр дүнтэй", "ru": "эффективный"},
  {"ko": "중심", "en": "center", "zh": "中心", "vi": "trung tâm", "mn": "төв", "ru": "центр"},
  {"ko": "기술하다", "en": "to describe", "zh": "记述", "vi": "miêu tả", "mn": "тодорхойлон бичих", "ru": "описывать"},
  {"ko": "입장", "en": "position", "zh": "立场", "vi": "lập trường", "mn": "байр суурь", "ru": "позиция"},
  {"ko": "객관적", "en": "objective", "zh": "客观", "vi": "khách quan", "mn": "бодитой", "ru": "объективный"},
  {"ko": "평가하다", "en": "to evaluate", "zh": "评价", "vi": "đánh giá", "mn": "үнэлэх", "ru": "оценивать"},
  {"ko": "포함시키다", "en": "to include", "zh": "包括", "vi": "bao gồm", "mn": "оруулах", "ru": "включать"},
  {"ko": "원하다", "en": "to want", "zh": "希望", "vi": "mong muốn", "mn": "хүсэх", "ru": "желать"},
  {"ko": "제시하다", "en": "to present", "zh": "提出", "vi": "trình bày", "mn": "танилцуулах", "ru": "представлять, предлагать"},
  {"ko": "바탕", "en": "basis", "zh": "基础", "vi": "nền tảng", "mn": "үндэс", "ru": "основа 서울대 한국어+ Student’s Book 4A 2  건강한 삶 Healthy Life 2-1    질병과 증상  Disease & Symptoms 한국어 표현 뜻 쪽"},
  {"ko": "가스가 차다", "en": "to be gassy", "zh": "胀气", "vi": "đầy hơi", "mn": "гэдэс дүүрэх", "ru": "вздутие живота"},
  {"ko": "피부가 가렵다", "en": "skin is itchy", "zh": "皮肤痒", "vi": "ngứa da", "mn": "арьс загатнах", "ru": "кожный зуд"},
  {"ko": "재채기를 하다", "en": "to sneeze", "zh": "打喷嚏", "vi": "hắt xì", "mn": "найтаах", "ru": "чихать 두드러기가 나다 /"},
  {"ko": "얼굴에 뭐가 나다", "en": "to have a rash / to have a facial breakout", "zh": "起荨麻疹 / 脸上长东西", "vi": "nổi mề đay / nổi mụn trên mặt", "mn": "чонон хөрвөс туурах / нүүрэн дээр юм гарах", "ru": "покрыться крапивницей / появились высыпания на лице"},
  {"ko": "눈이 건조하다 / 충혈되다", "en": "eyes are dry / bloodshot", "zh": "眼睛干涩 / 充血", "vi": "khô mắt / đau mắt đỏ", "mn": "нүд хуурайших / улайх", "ru": "сухость / покраснение глаз"},
  {"ko": "어깨가 / 목이 뻣뻣하다", "en": "to have stiff shoulders / to have a stiff neck", "zh": "肩膀 / 脖子僵硬", "vi": "mỏi vai / cổ bị cứng cơ", "mn": "мөр / хүзүү хөших", "ru": "затекли плечи / шея"},
  {"ko": "눈이 빠지다", "en": "eyes are popping out", "zh": "望眼欲穿", "vi": "đợi mỏi mòn, đợi dài cổ", "mn": "нүд унадаг", "ru": "глаза на лоб лезут"},
  {"ko": "머리가 깨지다", "en": "to have a splitting headache", "zh": "头要裂了", "vi": "đau đầu như búa bổ", "mn": "толгой хагарах", "ru": "голова раскалывается"},
  {"ko": "배가 터지다", "en": "stomach is bursting", "zh": "肚子要爆炸了", "vi": "no căng bụng", "mn": "гэдэс хагарах", "ru": "живот разрывается"},
  {"ko": "팔이 빠지다", "en": "to have a dislocated shoulder", "zh": "胳膊脱臼了", "vi": "mỏi rã rời tay", "mn": "гар мултрах", "ru": "рука отваливается"},
  {"ko": "귀가 떨어져 나가다", "en": "ears are falling off", "zh": "耳朵要冻掉了", "vi": "nhức tai (đau tai vì phải nghe ai đó nói quá lâu)", "mn": "чих хөлдөж унах", "ru": "уши отваливаются (например от холода)"},
  {"ko": "놀이기구", "en": "amusement park ride", "zh": "游乐设施", "vi": "trò chơi giải trí", "mn": "тоглоом", "ru": "аттракцион"},
  {"ko": "식은땀이 나다", "en": "to break out in a cold sweat", "zh": "出冷汗", "vi": "đổ mồ hôi lạnh", "mn": "хүйтэн хөлс гарах", "ru": "покрыться холодным потом"},
  {"ko": "환기", "en": "ventilation", "zh": "通风", "vi": "thông gió", "mn": "агаар сэлгэлт", "ru": "вентиляция"},
  {"ko": "꼼꼼히", "en": "thoroughly", "zh": "仔细地", "vi": "kỹ lưỡng", "mn": "нягт нямбай", "ru": "тщательно"},
  {"ko": "깜빡거리다", "en": "to blink", "zh": "眨眼", "vi": "nhấp nháy", "mn": "анивчих", "ru": "мигать"},
  {"ko": "쬐다", "en": "to bask", "zh": "晒", "vi": "tắm (nắng)", "mn": "ээх", "ru": "греться на солнце"},
  {"ko": "두드리다", "en": "to tap", "zh": "敲", "vi": "gõ", "mn": "тогших", "ru": "стучать"},
  {"ko": "스트레칭", "en": "stretching", "zh": "伸展运动", "vi": "giãn cơ", "mn": "сунгалтын дасгал", "ru": "растяжка"},
  {"ko": "특정하다", "en": "to be specific", "zh": "特定", "vi": "cụ thể", "mn": "тодорхойлох", "ru": "точно определенный, указанный"},
  {"ko": "반복적", "en": "repetitive", "zh": "反复的", "vi": "có tính lặp lại", "mn": "давтагдсан", "ru": "повторяющийся"},
  {"ko": "속이 거북하다", "en": "stomach is bloated", "zh": "胃里不舒服", "vi": "đầy bụng", "mn": "гэдэс царайх", "ru": "тяжесть в желудке"},
  {"ko": "한", "en": "approximate", "zh": "大约", "vi": "khoảng", "mn": "ойролцоогоор", "ru": "приблизительно"},
  {"ko": "아랫배", "en": "lower stomach", "zh": "下腹", "vi": "bụng dưới", "mn": "хэвлийн доод хэсэг", "ru": "низ живота"},
  {"ko": "살펴보다", "en": "to examine", "zh": "观察", "vi": "xem xét", "mn": "ажиглах", "ru": "осматривать"},
  {"ko": "원인", "en": "cause", "zh": "原因", "vi": "nguyên nhân", "mn": "шалтгаан", "ru": "причина"},
  {"ko": "대담", "en": "talk", "zh": "对话", "vi": "cuộc đối thoại", "mn": "ярилцлага", "ru": "беседа"},
  {"ko": "일상생활", "en": "everyday life", "zh": "日常生活", "vi": "cuộc sống hàng ngày", "mn": "өдөр тутмын амьдрал", "ru": "повседневная жизнь"},
  {"ko": "눈을 뜨다", "en": "to open one’s eyes", "zh": "睁开眼睛", "vi": "mở mắt", "mn": "нүдээ нээх", "ru": "открывать глаза"},
  {"ko": "노화", "en": "aging", "zh": "衰老", "vi": "lão hóa", "mn": "хөгшрөлт", "ru": "старение"},
  {"ko": "염증", "en": "inflammation", "zh": "炎症", "vi": "viêm", "mn": "үрэвсэл", "ru": "воспаление"},
  {"ko": "예방하다", "en": "to prevent", "zh": "预防", "vi": "phòng ngừa", "mn": "урьдчилан сэргийлэх", "ru": "предотвращать"},
  {"ko": "얼음찜질", "en": "ice massage", "zh": "冰敷", "vi": "chườm đá", "mn": "мөсөн жин", "ru": "ледяной компресс"},
  {"ko": "눈물이 흐르다", "en": "tears are falling", "zh": "流眼泪", "vi": "chảy nước mắt", "mn": "нулимс урсах", "ru": "слёзы текут"},
  {"ko": "마르다", "en": "to dry", "zh": "干", "vi": "khô", "mn": "хатах", "ru": "сохнуть"},
  {"ko": "인공", "en": "artificial", "zh": "人工", "vi": "nhân tạo", "mn": "хиймэл", "ru": "искусственный"},
  {"ko": "주위", "en": "surrounding", "zh": "周围", "vi": "xung quanh", "mn": "эргэн тойрон", "ru": "окружение"},
  {"ko": "없애다", "en": "to get rid of", "zh": "消除", "vi": "loại bỏ", "mn": "арилгах", "ru": "избавляться 2-2    건강한 습관 Healthy Habits 한국어 표현 뜻 쪽"},
  {"ko": "외식하다", "en": "to eat out", "zh": "在外面吃饭", "vi": "ăn ngoài", "mn": "гадуур хооллох", "ru": "есть вне дома"},
  {"ko": "과식하다", "en": "to overeat", "zh": "吃多了", "vi": "ăn quá nhiều", "mn": "хэтрүүлэн идэх", "ru": "переедать"},
  {"ko": "야식을 먹다", "en": "to have a late-night snack", "zh": "吃夜宵", "vi": "ăn khuya", "mn": "шөнө орой юм идэх", "ru": "есть на ночь"},
  {"ko": "짜게 / 달게 먹다", "en": "to eat salty / sweet", "zh": "吃咸的 / 甜的", "vi": "ăn mặn / ngọt", "mn": "давстай / чихэрлэг идэх", "ru": "есть солёное / сладкое"},
  {"ko": "기름진 음식을 먹다", "en": "to eat greasy food", "zh": "吃油腻的食物", "vi": "ăn đồ dầu mỡ", "mn": "тостой хоол идэх", "ru": "есть жирную пищу"},
  {"ko": "식사 시간이 불규칙하다", "en": "meal times are irregular", "zh": "吃饭时间不规律", "vi": "giờ ăn không đều đặn", "mn": "хооллох цаг тогтмол бус", "ru": "нерегулярное питание"},
  {"ko": "혈압이 높아지다", "en": "one’s blood pressure rises", "zh": "血压升高", "vi": "huyết áp tăng", "mn": "цусны даралт ихсэх", "ru": "давление повышается"},
  {"ko": "당뇨병에 걸리다", "en": "to develop diabetes", "zh": "得糖尿病", "vi": "mắc bệnh tiểu đường", "mn": "чихрийн шижинтэй болох", "ru": "заболеть диабетом"},
  {"ko": "충치가 생기다", "en": "to have a cavity", "zh": "长蛀牙", "vi": "bị sâu răng", "mn": "шүд хорхойтох", "ru": "появляется кариес"},
  {"ko": "비만이 되다", "en": "to become obese", "zh": "变胖", "vi": "mắc bệnh béo phì", "mn": "таргалах", "ru": "страдать ожирением"},
  {"ko": "위염에 걸리다", "en": "to develop gastritis", "zh": "得胃炎", "vi": "bị viêm dạ dày", "mn": "ходоодны үрэвсэлтэй болох", "ru": "заболеть гастритом"},
  {"ko": "나트륨", "en": "sodium", "zh": "钠", "vi": "natri", "mn": "натри", "ru": "натрий"},
  {"ko": "튀김", "en": "fried food", "zh": "油炸食品", "vi": "đồ chiên", "mn": "шарсан хоол", "ru": "блюдо во фритюре"},
  {"ko": "볶음", "en": "stir-fry", "zh": "炒菜", "vi": "món xào", "mn": "хуурсан хоол", "ru": "жареное блюдо"},
  {"ko": "젓갈", "en": "salted seafood", "zh": "酱菜", "vi": "mắm", "mn": "давсалсан далайн бүтээгдэхүүн", "ru": "ферментированные  / солёные морепродукты"},
  {"ko": "해당되다", "en": "to be applicable", "zh": "属于", "vi": "được phù hợp, được tương ứng", "mn": "хамаарагдах", "ru": "соответствовать"},
  {"ko": "칼럼", "en": "column", "zh": "专栏", "vi": "cột, mục", "mn": "нийтлэл", "ru": "колонка"},
  {"ko": "제때", "en": "regular times", "zh": "按时", "vi": "sự đúng giờ, đúng hẹn", "mn": "цагтаа", "ru": "вовремя"},
  {"ko": "현대인", "en": "modern people", "zh": "现代人", "vi": "người hiện đại", "mn": "орчин үеийн хүн", "ru": "современный человек"},
  {"ko": "뇌", "en": "brain", "zh": "脑", "vi": "não", "mn": "тархи", "ru": "мозг"},
  {"ko": "식욕", "en": "appetite", "zh": "食欲", "vi": "sự thèm ăn", "mn": "хоолны дуршил", "ru": "аппетит"},
  {"ko": "육류", "en": "meat", "zh": "肉类", "vi": "các loại thịt", "mn": "махан бүтээгдэхүүн", "ru": "мясо  / мясные продукты"},
  {"ko": "매끼", "en": "every meal", "zh": "每顿饭", "vi": "mỗi bữa ăn", "mn": "хоол болгон", "ru": "каждый приём пищи"},
  {"ko": "적당히", "en": "moderately", "zh": "适当地", "vi": "một cách vừa phải", "mn": "тохиромжтой", "ru": "умеренно"},
  {"ko": "섭취하다", "en": "to intake", "zh": "摄取", "vi": "hấp thụ", "mn": "хэрэглэх", "ru": "потреблять"},
  {"ko": "끼", "en": "counting unit for meals", "zh": "顿", "vi": "bữa", "mn": "удаа", "ru": "приём пищи (счётное слово)"},
  {"ko": "하루치", "en": "one day’s proportion", "zh": "一天的量", "vi": "khẩu phần một ngày", "mn": "нэг өдрийн хэмжээ", "ru": "дневная норма"},
  {"ko": "어쩔 수 없다", "en": "to be unavoidable", "zh": "没办法", "vi": "không thể tránh khỏi", "mn": "аргагүй", "ru": "ничего не поделаешь"},
  {"ko": "오이", "en": "cucumber", "zh": "黄瓜", "vi": "dưa chuột", "mn": "өргөст хэмх", "ru": "огурец"},
  {"ko": "유지", "en": "maintenance", "zh": "维持", "vi": "duy trì", "mn": "хадгалах", "ru": "поддержание"},
  {"ko": "연결하다", "en": "to connect", "zh": "连接", "vi": "kết nối", "mn": "холбох", "ru": "соединять"},
  {"ko": "열량", "en": "calories", "zh": "热量", "vi": "calo", "mn": "илчлэг", "ru": "калории"},
  {"ko": "당류", "en": "sugars", "zh": "糖类", "vi": "các loại đường", "mn": "чихэрлэг зүйлс", "ru": "сахара"},
  {"ko": "권장량", "en": "recommended amount", "zh": "推荐量", "vi": "lượng khuyến nghị", "mn": "зөвлөсөн хэмжээ", "ru": "рекомендуемое количество"},
  {"ko": "팥빙수", "en": "red bean shaved ice", "zh": "红豆冰沙", "vi": "patbingsu (đá bào đậu đỏ)", "mn": "будааны мөстэй зууш", "ru": "патбинсу (ледяная стружка с красной фасолью)"},
  {"ko": "짜장면", "en": "black bean sauce noodles", "zh": "炸酱面", "vi": "mì tương đen", "mn": "хар сүмстэй гоймон", "ru": "чачжанмён (лапша с чёрным соусом)"},
  {"ko": "포스터", "en": "poster", "zh": "海报", "vi": "áp phích", "mn": "зурагт хуудас", "ru": "плакат"},
  {"ko": "경고", "en": "warning", "zh": "警告", "vi": "cảnh báo", "mn": "анхааруулга", "ru": "предупреждение 서울대 한국어+ Student’s Book 4A 3  선택과 변화 Choices & Changes 3-1    만족과 후회  Satisfaction & Regret 한국어 표현 뜻 쪽"},
  {"ko": "만족스럽다", "en": "to be satisfied", "zh": "满意", "vi": "hài lòng", "mn": "сэтгэл хангалуун", "ru": "быть удовлетворённым"},
  {"ko": "자랑스럽다", "en": "to be proud", "zh": "自豪", "vi": "tự hào", "mn": "бахархмаар", "ru": "гордиться"},
  {"ko": "즐기다", "en": "to enjoy", "zh": "享受", "vi": "tận hưởng", "mn": "таашаал авах", "ru": "наслаждаться 보람을 느끼다 /"},
  {"ko": "보람이 있다", "en": "to feel rewarded / to be rewarded", "zh": "感到有意义", "vi": "cảm thấy xứng đáng / có ý nghĩa", "mn": "урам авах / урамтай", "ru": "чувствовать удовлетворение, быть стóящим"},
  {"ko": "자신감이 생기다", "en": "to gain confidence", "zh": "产生自信", "vi": "có được sự tự tin", "mn": "өөртөө итгэлтэй болох", "ru": "обрести уверенность"},
  {"ko": "괴롭다", "en": "to be distressed", "zh": "痛苦", "vi": "đau khổ", "mn": "зовох", "ru": "страдать"},
  {"ko": "실망스럽다", "en": "to be disappointing", "zh": "令人失望", "vi": "đáng thất vọng", "mn": "урам хугарах", "ru": "разочаровывающий"},
  {"ko": "아쉽다", "en": "to be a pity", "zh": "可惜", "vi": "đáng tiếc", "mn": "харамсалтай", "ru": "жаль"},
  {"ko": "후회스럽다", "en": "to be regretful", "zh": "后悔", "vi": "hối tiếc", "mn": "харамсалтай", "ru": "сожалеть"},
  {"ko": "엉망이다 / 엉망이 되다", "en": "to ruin / to be ruined", "zh": "乱七八糟 / 变得一团糟", "vi": "bừa bộn / trở nên bừa bộn", "mn": "замбараагүй / замбараагүй болох", "ru": "быть в беспорядке / превратиться в беспорядок"},
  {"ko": "봉사활동", "en": "volunteer work", "zh": "志愿活动", "vi": "hoạt động tình nguyện", "mn": "сайн дурын ажил", "ru": "волонтёрская деятельность"},
  {"ko": "다행이다", "en": "to be a relief", "zh": "幸好", "vi": "thật may mắn", "mn": "ашгүй дээ", "ru": "к счастью"},
  {"ko": "나아지다", "en": "to become better", "zh": "变好", "vi": "trở nên tốt hơn", "mn": "дээрдэх", "ru": "улучшаться"},
  {"ko": "그러다가", "en": "and then", "zh": "然后", "vi": "rồi thì", "mn": "тэгж байгаад", "ru": "затем"},
  {"ko": "얼마 후에", "en": "before long", "zh": "不久之后", "vi": "một thời gian sau", "mn": "удалгүй", "ru": "вскоре"},
  {"ko": "결국", "en": "eventually", "zh": "最终", "vi": "cuối cùng", "mn": "эцэст нь", "ru": "в конце концов"},
  {"ko": "신인", "en": "rookie", "zh": "新人", "vi": "tân binh", "mn": "шинэ хүн", "ru": "новичок"},
  {"ko": "출신", "en": "from (origin)", "zh": "出身", "vi": "xuất thân", "mn": "гаралтай", "ru": "происхождение"},
  {"ko": "욕을 먹다", "en": "to be insulted", "zh": "被骂", "vi": "bị chửi", "mn": "зэмлэл хүлээх", "ru": "быть обруганным"},
  {"ko": "망설이다", "en": "to hesitate", "zh": "犹豫", "vi": "do dự", "mn": "эргэлзэх", "ru": "колебаться"},
  {"ko": "평생", "en": "lifetime", "zh": "一生", "vi": "cả đời", "mn": "насан турш", "ru": "вся жизнь"},
  {"ko": "글씨", "en": "handwriting", "zh": "字迹", "vi": "chữ viết tay", "mn": "бичиг", "ru": "почерк"},
  {"ko": "신경이 쓰이다", "en": "to be on one’s mind", "zh": "操心", "vi": "bận tâm", "mn": "санаа зовох", "ru": "беспокоиться"},
  {"ko": "교본", "en": "textbook", "zh": "教科书", "vi": "sách giáo khoa", "mn": "сурах бичиг", "ru": "учебник"},
  {"ko": "사건", "en": "event", "zh": "事件", "vi": "sự kiện", "mn": "үйл явдал", "ru": "событие"},
  {"ko": "흐름", "en": "flow", "zh": "流程", "vi": "dòng chảy", "mn": "урсгал", "ru": "поток"},
  {"ko": "감정", "en": "feeling", "zh": "感情", "vi": "cảm xúc", "mn": "сэтгэл хөдлөл", "ru": "чувство"},
  {"ko": "호감", "en": "good feeling", "zh": "好感", "vi": "thiện cảm", "mn": "таатай сэтгэгдэл", "ru": "симпатия"},
  {"ko": "첫인상", "en": "first impression", "zh": "第一印象", "vi": "ấn tượng đầu tiên", "mn": "анхны сэтгэгдэл", "ru": "первое впечатление"},
  {"ko": "활동적", "en": "active", "zh": "活跃", "vi": "năng động", "mn": "идэвхтэй", "ru": "активный"},
  {"ko": "마음을 접다", "en": "to stop liking someone / something", "zh": "死心", "vi": "từ bỏ, bỏ cuộc", "mn": "сэтгэлээ татах", "ru": "отказаться от чувств"},
  {"ko": "군대에 가다", "en": "to join the military", "zh": "去当兵", "vi": "đi nhập ngũ", "mn": "цэрэгт явах", "ru": "идти в армию"},
  {"ko": "마주치다", "en": "to run into", "zh": "碰到", "vi": "chạm mặt", "mn": "тааралдах", "ru": "столкнуться"},
  {"ko": "안타깝다", "en": "to be pitiful", "zh": "惋惜", "vi": "đáng tiếc", "mn": "харамсалтай", "ru": "жаль"},
  {"ko": "신청곡", "en": "song request", "zh": "点歌", "vi": "bài hát được thính giả yêu cầu", "mn": "хүсэлтийн дуу", "ru": "песня по заявке"},
  {"ko": "과정", "en": "process", "zh": "过程", "vi": "quá trình", "mn": "үйл явц", "ru": "процесс 3-2    사회 변화 Social Change 한국어 표현 뜻 쪽"},
  {"ko": "생각이 반영되다", "en": "thoughts are reflected", "zh": "反映想法", "vi": "suy nghĩ được phản ánh", "mn": "бодол тусгагдах", "ru": "мысли отражаются"},
  {"ko": "사고방식이 변화하다", "en": "mindset is changed", "zh": "思维方式改变", "vi": "thay đổi lối suy nghĩ", "mn": "сэтгэхүй өөрчлөгдөх", "ru": "мышление меняется"},
  {"ko": "바탕이 되다", "en": "to be based on", "zh": "成为基础", "vi": "làm nền tảng", "mn": "үндэс болох", "ru": "служить основой"},
  {"ko": "영향을 주다 / 끼치다", "en": "to affect / to have an effect on", "zh": "产生影响", "vi": "gây ảnh hưởng", "mn": "нөлөө үзүүлэх", "ru": "оказывать влияние"},
  {"ko": "영향을 받다", "en": "to be affected", "zh": "受到影响", "vi": "bị ảnh hưởng", "mn": "нөлөөнд автах", "ru": "подвергаться влиянию"},
  {"ko": "비정상(적)", "en": "abnormal", "zh": "不正常", "vi": "tính bất thường", "mn": "хэвийн бус", "ru": "ненормальный"},
  {"ko": "비공개(적)", "en": "private", "zh": "不公开", "vi": "không công khai", "mn": "нууц", "ru": "непубличный"},
  {"ko": "비현실적", "en": "unrealistic", "zh": "不现实", "vi": "tính phi thực tế", "mn": "бодит бус", "ru": "нереалистичный"},
  {"ko": "비전문적", "en": "unprofessional", "zh": "不专业", "vi": "tính không chuyên nghiệp, tính không chuyên môn", "mn": "мэргэжлийн бус", "ru": "непрофессиональный"},
  {"ko": "비대면", "en": "non face-to-face", "zh": "非接触", "vi": "không gặp mặt trước tiếp", "mn": "нүүр тулаагүй", "ru": "дистанционный, бесконтактный"},
  {"ko": "요약하다", "en": "to summarize", "zh": "总结", "vi": "tóm tắt", "mn": "хураангуйлах", "ru": "подводить итог"},
  {"ko": "응답하다", "en": "to respond", "zh": "回答", "vi": "trả lời", "mn": "хариулах", "ru": "отвечать"},
  {"ko": "흔히", "en": "commonly", "zh": "常常", "vi": "thường", "mn": "ихэвчлэн", "ru": "обычно"},
  {"ko": "어딘가", "en": "somewhere", "zh": "某处", "vi": "ở đâu đó", "mn": "хаа нэгтээ", "ru": "где-то"},
  {"ko": "실제로", "en": "in reality", "zh": "实际上", "vi": "trên thực tế", "mn": "бодит байдал дээр", "ru": "на самом деле"},
  {"ko": "증가하다", "en": "to increase", "zh": "增加", "vi": "tăng", "mn": "нэмэгдэх", "ru": "увеличиваться"},
  {"ko": "정상적", "en": "normal", "zh": "正常的", "vi": "tính bình thường", "mn": "хэвийн", "ru": "нормальный"},
  {"ko": "삶", "en": "life", "zh": "生活", "vi": "cuộc sống", "mn": "амьдрал", "ru": "жизнь"},
  {"ko": "선호되다", "en": "to be preferred", "zh": "偏爱", "vi": "được ưa chuộng", "mn": "илүүд үзэгдэх", "ru": "быть предпочитаемым"},
  {"ko": "필요성", "en": "necessity", "zh": "必要性", "vi": "sự cần thiết", "mn": "хэрэгцээ", "ru": "необходимость"},
  {"ko": "매체", "en": "media", "zh": "媒体", "vi": "phương tiện truyền thông", "mn": "хэвлэл мэдээлэл", "ru": "СМИ"},
  {"ko": "손쉽다", "en": "to be easy", "zh": "容易", "vi": "dễ dàng", "mn": "амархан", "ru": "лёгкий"},
  {"ko": "지식", "en": "knowledge", "zh": "知识", "vi": "tri thức", "mn": "мэдлэг", "ru": "знание"},
  {"ko": "과외", "en": "private lesson", "zh": "课外辅导", "vi": "học thêm", "mn": "нэмэлт хичээл", "ru": "частный урок"},
  {"ko": "단순히", "en": "simply", "zh": "单纯地", "vi": "một cách đơn giản", "mn": "зүгээр л", "ru": "просто"},
  {"ko": "의사소통하다", "en": "to communicate", "zh": "沟通", "vi": "giao tiếp", "mn": "харилцан ойлголцох", "ru": "общаться"},
  {"ko": "부딪히다", "en": "to bump into", "zh": "碰撞", "vi": "va chạm", "mn": "мөргөлдөх", "ru": "сталкиваться"},
  {"ko": "맺다", "en": "to form", "zh": "建立", "vi": "hình thành", "mn": "үүсгэх", "ru": "формировать"},
  {"ko": "수준", "en": "level", "zh": "水平", "vi": "trình độ, tiêu chuẩn", "mn": "түвшин", "ru": "уровень"},
  {"ko": "형성", "en": "formation", "zh": "形成", "vi": "sự hình thành", "mn": "бүрэлдэн тогтох", "ru": "формирование"},
  {"ko": "한계", "en": "limit", "zh": "界限", "vi": "giới hạn", "mn": "хязгаар", "ru": "предел"},
  {"ko": "당연하다", "en": "to be natural", "zh": "当然", "vi": "đương nhiên", "mn": "мэдээжийн хэрэг", "ru": "естественный 서울대 한국어+ Student’s Book 4A 4  기후와 문화 Climate & Culture 4-1    날씨와 기후  Weather & Climate 한국어 표현 뜻 쪽"},
  {"ko": "쌀쌀하다", "en": "to be chilly", "zh": "凉飕飕", "vi": "se lạnh", "mn": "сэрүүхэн", "ru": "прохладный"},
  {"ko": "포근하다", "en": "to be warm", "zh": "温暖", "vi": "ấm áp", "mn": "дулаахан", "ru": "тёплый"},
  {"ko": "날씨가 변덕스럽다", "en": "weather is unpredictable", "zh": "天气多变", "vi": "thời tiết thất thường", "mn": "цаг агаар тогтворгүй", "ru": "погода переменчива"},
  {"ko": "비바람이 불다", "en": "rain and wind are blowing", "zh": "刮风下雨", "vi": "cơn mưa dông", "mn": "салхи шуургатай", "ru": "дует ветер с дождём"},
  {"ko": "일교차가 크다", "en": "temperature changes are drastic", "zh": "温差大", "vi": "chênh lệch nhiệt độ lớn", "mn": "өдөр шөнийн температурын зөрүү их", "ru": "большая разница температур"},
  {"ko": "햇볕이 뜨겁다", "en": "sunshine is hot", "zh": "阳光火辣", "vi": "nắng gắt", "mn": "нар шарах", "ru": "палящее солнце"},
  {"ko": "폭설이 쏟아지다", "en": "snowing heavily", "zh": "下暴雪", "vi": "tuyết rơi dày", "mn": "их цас орох", "ru": "идёт сильный снег"},
  {"ko": "폭우가 내리다", "en": "raining heavily", "zh": "下暴雨", "vi": "mưa lớn", "mn": "аадар бороо орох", "ru": "идёт сильный дождь"},
  {"ko": "폭염이 계속되다", "en": "heatwave continues", "zh": "酷暑持续", "vi": "nắng nóng kéo dài", "mn": "халуун үргэлжлэх", "ru": "жара продолжается"},
  {"ko": "폭풍이 불다", "en": "storm blows", "zh": "刮暴风", "vi": "bão", "mn": "шуурга шуурах", "ru": "дует шторм"},
  {"ko": "폭풍우가 치다", "en": "rainstorm is hitting", "zh": "暴风雨来袭", "vi": "bão tố", "mn": "шуурга дэгдэх", "ru": "бушует шторм"},
  {"ko": "선글라스", "en": "sunglasses", "zh": "墨镜", "vi": "kính râm", "mn": "нарны шил", "ru": "солнцезащитные очки"},
  {"ko": "계단", "en": "stairs", "zh": "楼梯", "vi": "cầu thang", "mn": "шат", "ru": "лестница"},
  {"ko": "분실물 센터", "en": "Lost and Found Center", "zh": "失物招领处", "vi": "trung tâm đồ thất lạc", "mn": "гээгдүүлсэн эд зүйлсийн төв", "ru": "бюро находок"},
  {"ko": "곤란하다", "en": "to be difficult", "zh": "为难", "vi": "khó xử", "mn": "хэцүү", "ru": "быть в затруднении"},
  {"ko": "평년", "en": "average year", "zh": "平年", "vi": "năm thường", "mn": "жирийн жил", "ru": "обычный год"},
  {"ko": "일교차가 벌어지다", "en": "to have a wide daily temperature difference", "zh": "温差拉大", "vi": "chênh lệch nhiệt độ ngày đêm lớn", "mn": "өдөр шөнийн температурын зөрүү гарах", "ru": "возникает большая разница температур"},
  {"ko": "대비하다", "en": "to prepare", "zh": "准备", "vi": "đối phó, phòng bị", "mn": "бэлдэх", "ru": "готовиться, принимать меры"},
  {"ko": "대체로", "en": "mostly", "zh": "大体上", "vi": "nhìn chung", "mn": "ерөнхийдөө", "ru": "в основном"},
  {"ko": "기후", "en": "climate", "zh": "气候", "vi": "khí hậu", "mn": "уур амьсгал", "ru": "климат"},
  {"ko": "잠기다", "en": "to be submerged", "zh": "淹没", "vi": "ngập", "mn": "живэх", "ru": "быть затопленным"},
  {"ko": "벌어지다", "en": "to happen", "zh": "发生", "vi": "xảy ra", "mn": "болох", "ru": "происходить"},
  {"ko": "예측하다", "en": "to predict", "zh": "预测", "vi": "dự đoán", "mn": "таамаглах", "ru": "предсказывать"},
  {"ko": "갑작스럽다", "en": "to be unexpected", "zh": "突然", "vi": "đột ngột", "mn": "гэнэтийн", "ru": "внезапный"},
  {"ko": "일부", "en": "some", "zh": "一部分", "vi": "một bộ phận", "mn": "зарим хэсэг", "ru": "часть"},
  {"ko": "극단적이다", "en": "to be extreme", "zh": "极端的", "vi": "cực đoan", "mn": "туйлын", "ru": "экстремальный"},
  {"ko": "전문가", "en": "expert", "zh": "专家", "vi": "chuyên gia", "mn": "мэргэжилтэн", "ru": "эксперт"},
  {"ko": "절반", "en": "half", "zh": "一半", "vi": "một nửa", "mn": "хагас", "ru": "половина"},
  {"ko": "가뭄", "en": "drought", "zh": "干旱", "vi": "hạn hán", "mn": "ган", "ru": "засуха"},
  {"ko": "피해", "en": "damage", "zh": "损失", "vi": "thiệt hại", "mn": "хохирол", "ru": "ущерб"},
  {"ko": "홍수", "en": "flood", "zh": "洪水", "vi": "lũ lụt", "mn": "үер", "ru": "наводнение"},
  {"ko": "폐쇄되다", "en": "to be shut down", "zh": "被关闭", "vi": "bị đóng cửa, bị phong tỏa", "mn": "хаагдах", "ru": "быть закрытым"},
  {"ko": "불편을 겪다", "en": "to experience inconvenience", "zh": "感到不适", "vi": "gặp bất tiện", "mn": "хүндрэл учрах", "ru": "испытывать неудобства 4-2    기후와 문화의 특징 Climate & Characteristics of Culture 한국어 표현 뜻 쪽"},
  {"ko": "건조하다", "en": "to be dry", "zh": "干燥", "vi": "khô", "mn": "хуурай", "ru": "сухой"},
  {"ko": "강수량이 많다 / 적다", "en": "precipitation is high / low", "zh": "降雨量多 / 少", "vi": "lượng mưa nhiều / ít", "mn": "хур тунадас их / бага", "ru": "высокое / низкое количество осадков"},
  {"ko": "습도가 높다", "en": "humidity is high", "zh": "湿度高", "vi": "độ ẩm cao", "mn": "чийгшил ихтэй", "ru": "высокая влажность"},
  {"ko": "서늘하다", "en": "to be cool", "zh": "凉爽", "vi": "mát mẻ", "mn": "сэрүүн", "ru": "прохладный"},
  {"ko": "더위가 / 추위가 심하다", "en": "heat / cold is severe", "zh": "酷暑 / 严寒", "vi": "nóng / lạnh khắc nghiệt", "mn": "халуун / хүйтэн ихтэй", "ru": "сильная жара / сильный холод"},
  {"ko": "사계절이 뚜렷하다", "en": "four seasons are distinct", "zh": "四季分明", "vi": "bốn mùa rõ rệt", "mn": "дөрвөн улирал тод", "ru": "четыре времени года чётко выражены"},
  {"ko": "생소하다", "en": "to be unfamiliar", "zh": "陌生", "vi": "xa lạ, lạ lẫm, mới mẻ", "mn": "танил бус", "ru": "незнакомый"},
  {"ko": "독특하다", "en": "to be unique", "zh": "独特", "vi": "độc đáo", "mn": "өвөрмөц", "ru": "уникальный"},
  {"ko": "친숙하다", "en": "to be familiar", "zh": "熟悉", "vi": "thân thuộc", "mn": "дотно", "ru": "знакомый"},
  {"ko": "차이가 있다", "en": "to have a difference", "zh": "有差异", "vi": "có sự khác biệt", "mn": "ялгаатай", "ru": "есть разница"},
  {"ko": "공통점이 있다", "en": "to have common ground", "zh": "有共同点", "vi": "có điểm chung", "mn": "нийтлэг талтай", "ru": "иметь общее"},
  {"ko": "구조", "en": "structure", "zh": "结构", "vi": "cấu trúc", "mn": "бүтэц", "ru": "структура"},
  {"ko": "북부", "en": "northern", "zh": "北部", "vi": "phía bắc", "mn": "хойд", "ru": "северный"},
  {"ko": "대청", "en": "a large wooden floor", "zh": "大厅", "vi": "đại sảnh (sàn gỗ)", "mn": "том модон шал", "ru": "тэчхон (большой зал в традиционном корейском доме)"},
  {"ko": "외양간", "en": "barn", "zh": "牛棚", "vi": "chuồng bò", "mn": "үхрийн саравч", "ru": "хлев"},
  {"ko": "중부", "en": "central", "zh": "中部", "vi": "miền trung", "mn": "төвийн", "ru": "центральная часть"},
  {"ko": "건넌방", "en": "opposite room", "zh": "对面房间", "vi": "phòng đối diện", "mn": "эсрэг талын өрөө", "ru": "комната напротив"},
  {"ko": "창고", "en": "storage", "zh": "仓库", "vi": "nhà kho", "mn": "агуулах", "ru": "склад"},
  {"ko": "남부", "en": "southern", "zh": "南部", "vi": "phía nam", "mn": "өмнөд", "ru": "южный"},
  {"ko": "재배지", "en": "cultivation area", "zh": "栽培地", "vi": "đất trồng trọt, đất canh tác", "mn": "тариалангийн талбай", "ru": "место выращивания"},
  {"ko": "재배하다", "en": "to cultivate", "zh": "栽培", "vi": "trồng trọt", "mn": "тариалах", "ru": "выращивать"},
  {"ko": "수출하다", "en": "to export", "zh": "出口", "vi": "xuất khẩu", "mn": "экспортлох", "ru": "экспортировать"},
  {"ko": "설명문", "en": "expository writing", "zh": "说明文", "vi": "văn bản thuyết minh", "mn": "тайлбар бичиг", "ru": "пояснительный текст"},
  {"ko": "즉", "en": "in other words", "zh": "也就是", "vi": "tức là", "mn": "өөрөөр хэлбэл", "ru": "то есть"},
  {"ko": "산간", "en": "between mountains", "zh": "山间", "vi": "miền núi", "mn": "уулархаг нутаг", "ru": "горный район"},
  {"ko": "고춧가루", "en": "red pepper powder", "zh": "辣椒粉", "vi": "bột ớt", "mn": "улаан чинжүүний нунтаг", "ru": "молотый красный перец"},
  {"ko": "넉넉하다", "en": "to be abundant", "zh": "充裕", "vi": "dồi dào", "mn": "элбэг", "ru": "обильный"},
  {"ko": "관련성", "en": "relation", "zh": "相关性", "vi": "sự liên quan", "mn": "холбоо хамаарал", "ru": "связь"},
  {"ko": "밀", "en": "wheat", "zh": "小麦", "vi": "lúa mì", "mn": "улаан буудай", "ru": "пшеница"},
  {"ko": "보리", "en": "barley", "zh": "大麦", "vi": "lúa mạch", "mn": "арвай", "ru": "ячмень"},
  {"ko": "주식", "en": "staple (food)", "zh": "主食", "vi": "lương thực chính", "mn": "үндсэн хоол", "ru": "основной продукт питания 서울대 한국어+ Student’s Book 4A 5  여행의 즐거움 Delight of Travel 5-1    아름다운 풍경  Beautiful Scenery 한국어 표현 뜻 쪽"},
  {"ko": "눈꽃이 피다", "en": "snowflakes bloom", "zh": "雪花绽放", "vi": "tuyết nở hoa", "mn": "цасан ширхэг будрах", "ru": "снежные цветы распускаются (о деревьях в инее или заснеженных пейзажах)"},
  {"ko": "단풍잎이 떨어지다", "en": "autumn leaves fall", "zh": "枫叶飘落", "vi": "lá phong rụng", "mn": "шар навч унах", "ru": "осенние листья падают"},
  {"ko": "해가 / 달이 / 별이 뜨다", "en": "sun / moon / star rises", "zh": "日 / 月 / 星升起", "vi": "mặt trời / mặt trăng / ngôi sao mọc", "mn": "нар / сар / од гарах", "ru": "солнце / луна / звезда всходит"},
  {"ko": "별이 / 해가 / 달이 지다", "en": "star / sun / moon sets", "zh": "星 / 日 / 月落山", "vi": "ngôi sao / mặt trời / mặt trăng lặn", "mn": "од / нар / сар жаргах", "ru": "звезда / солнце / луна заходит"},
  {"ko": "달빛이 / 햇빛이 비치다", "en": "moonlight / sunlight shines", "zh": "月光 / 阳光照耀", "vi": "ánh trăng / ánh nắng chiếu rọi", "mn": "сарны / нарны гэрэл тусах", "ru": "лунный / солнечный свет светит"},
  {"ko": "노랗게 / 빨갛게 물들다", "en": "to be stained yellow / red", "zh": "染成黄色 / 红色", "vi": "nhuộm vàng / đỏ", "mn": "шаргал / улаан өнгөөр хучигдах", "ru": "окрашиваться в жёлтый / красный цвет"},
  {"ko": "꽃으로 / 별로 가득하다", "en": "to be full of flowers / stars", "zh": "充满鲜花 / 星星", "vi": "đầy hoa / sao", "mn": "цэцгээр / одоор дүүрэн", "ru": "быть полным цветов / звёзд 불빛이 / 별빛이"},
  {"ko": "반짝거리다", "en": "lights / starlights twinkle", "zh": "灯光 / 星光闪烁", "vi": "ánh đèn / ánh sao lấp lánh", "mn": "гэрэл / од гялалзах", "ru": "огни / звёзды мерцают 꽃잎이 / 낙엽이"},
  {"ko": "바람에 날리다", "en": "petals / fallen leaves blow in the wind", "zh": "花瓣 / 落叶随风飘扬", "vi": "cánh hoa / lá rụng bay trong gió", "mn": "цэцгийн дэлбээ / навч салхинд хийсэх", "ru": "лепестки / опавшие листья летят по ветру 사막이 / 바다가 / 초원이"},
  {"ko": "펼쳐지다", "en": "desert / ocean / meadow unfolds", "zh": "沙漠 / 大海 / 草原在眼前呈现", "vi": "sa mạc / biển / đồng cỏ trải dài", "mn": "цөл / далай / тал нутаг харагдах", "ru": "пустыня / море / степь простирается 건물로 / 산으로"},
  {"ko": "둘러싸이다", "en": "to be surrounded by buildings / mountains", "zh": "被建筑物 / 山环绕", "vi": "được bao quanh bởi các tòa nhà / núi", "mn": "барилга / уулаар хүрээлэгдэх", "ru": "быть окружённым зданиями / горами"},
  {"ko": "묘사하다", "en": "to describe", "zh": "描写", "vi": "miêu tả", "mn": "дүрслэх", "ru": "описывать"},
  {"ko": "야경", "en": "night view", "zh": "夜景", "vi": "cảnh đêm", "mn": "шөнийн үзэмж", "ru": "ночной вид"},
  {"ko": "도자기", "en": "pottery", "zh": "陶瓷", "vi": "đồ gốm", "mn": "шавар эдлэл", "ru": "керамика"},
  {"ko": "조각", "en": "sculpture", "zh": "雕塑", "vi": "điêu khắc", "mn": "уран баримал", "ru": "скульптура"},
  {"ko": "신비롭다", "en": "to be mysterious", "zh": "神秘", "vi": "huyền bí", "mn": "нууцлаг", "ru": "таинственный"},
  {"ko": "자세히", "en": "in detail", "zh": "详细地", "vi": "chi tiết", "mn": "нарийвчлан", "ru": "подробно"},
  {"ko": "숲길", "en": "forest road", "zh": "林间小路", "vi": "đường rừng", "mn": "ойн зам", "ru": "лесная тропа"},
  {"ko": "담다", "en": "to put into", "zh": "装", "vi": "đựng", "mn": "хийх", "ru": "класть"},
  {"ko": "왕복", "en": "round trip", "zh": "往返", "vi": "khứ hồi", "mn": "ирж очих", "ru": "туда и обратно"},
  {"ko": "운행하다", "en": "to operate", "zh": "运行", "vi": "vận hành", "mn": "ажиллах", "ru": "работать (о транспорте)"},
  {"ko": "바깥", "en": "outside", "zh": "外面", "vi": "bên ngoài", "mn": "гадаа", "ru": "снаружи"},
  {"ko": "코스", "en": "course", "zh": "路线", "vi": "tuyến đường", "mn": "чиглэл", "ru": "курс"},
  {"ko": "마주", "en": "facing", "zh": "面对面", "vi": "đối diện", "mn": "нүүр тулан", "ru": "лицом к лицу"},
  {"ko": "바라보다", "en": "to look at", "zh": "凝视", "vi": "nhìn", "mn": "харах", "ru": "смотреть"},
  {"ko": "확", "en": "completely", "zh": "一下子", "vi": "hết", "mn": "шууд", "ru": "полностью"},
  {"ko": "곡", "en": "counting uint for song", "zh": "首", "vi": "bài", "mn": "дуу (тоолох нэгж)", "ru": "песня (счётное слово)"},
  {"ko": "토의하다", "en": "to discuss", "zh": "讨论", "vi": "thảo luận", "mn": "хэлэлцэх", "ru": "обсуждать"},
  {"ko": "일단", "en": "first", "zh": "首先", "vi": "trước tiên", "mn": "юуны түрүүнд", "ru": "сначала"},
  {"ko": "하룻밤", "en": "one night", "zh": "一晚", "vi": "một đêm", "mn": "нэг шөнө", "ru": "одна ночь"},
  {"ko": "기분이 상쾌하다", "en": "feeling refreshed", "zh": "心情舒畅", "vi": "cảm thấy sảng khoái", "mn": "сэтгэл сэргэх", "ru": "чувствовать себя бодрым"},
  {"ko": "기분이 색다르다", "en": "feeling different", "zh": "心情新奇", "vi": "cảm thấy khác lạ", "mn": "сэтгэл сэргэх", "ru": "чувствовать что-то новое"},
  {"ko": "기분이 상하다", "en": "feeling offended", "zh": "心情不好", "vi": "cảm thấy bị xúc phạm", "mn": "сэтгэл дундуур байх", "ru": "быть обиженным"},
  {"ko": "마음이 들뜨다", "en": "feeling excited", "zh": "心情激动", "vi": "lòng nao nức", "mn": "сэтгэл догдлох", "ru": "быть взволнованным"},
  {"ko": "마음이 차분해지다", "en": "feeling calm", "zh": "心情平静下来", "vi": "lòng bình tĩnh lại", "mn": "сэтгэл тайвшрах", "ru": "успокаиваться"},
  {"ko": "마음이 우울해지다", "en": "feeling depressed", "zh": "心情郁闷", "vi": "lòng u uất", "mn": "сэтгэл гутрах", "ru": "впадать в депрессию"},
  {"ko": "끝없이", "en": "endlessly", "zh": "无尽地", "vi": "vô tận", "mn": "эцэс төгсгөлгүй", "ru": "бесконечно"},
  {"ko": "수없이", "en": "countlessly", "zh": "无数地", "vi": "vô số", "mn": "тоо томшгүй", "ru": "бесчисленно"},
  {"ko": "말없이", "en": "wordlessly", "zh": "默默地", "vi": "chẳng nói chẳng rằng, một cách yên lặng", "mn": "дуугүй", "ru": "безмолвно"},
  {"ko": "쓸데없이", "en": "unnecessarily", "zh": "毫无必要地", "vi": "một cách vô ích", "mn": "хэрэггүй", "ru": "без надобности"},
  {"ko": "정신없이", "en": "hectically", "zh": "忙乱地", "vi": "bận túi bụi", "mn": "завгүй", "ru": "суматошно"},
  {"ko": "자료", "en": "material", "zh": "资料", "vi": "tài liệu", "mn": "материал", "ru": "материал"},
  {"ko": "지인", "en": "acquaintance", "zh": "熟人", "vi": "người quen", "mn": "танил", "ru": "знакомый"},
  {"ko": "인터넷 사이트", "en": "internet site", "zh": "网站", "vi": "trang web", "mn": "вэб сайт", "ru": "интернет-сайт"},
  {"ko": "모바일", "en": "mobile", "zh": "移动", "vi": "di động", "mn": "гар утас", "ru": "мобильный"},
  {"ko": "도보", "en": "walking", "zh": "步行", "vi": "đi bộ", "mn": "явган", "ru": "пешком"},
  {"ko": "다도", "en": "tea ceremony", "zh": "茶道", "vi": "trà đạo", "mn": "цайны ёслол", "ru": "чайная церемония"},
  {"ko": "최대", "en": "maximum", "zh": "最大", "vi": "tối đa", "mn": "хамгийн их", "ru": "максимум"},
  {"ko": "한지공예", "en": "Korean paper art", "zh": "韩纸工艺", "vi": "thủ công giấy Hanji", "mn": "солонгос цаасан урлал", "ru": "искусство корейской бумаги"},
  {"ko": "채", "en": "counting unit for house / building", "zh": "栋", "vi": "căn (đơn vị tính căn nhà)", "mn": "байшин (тоолох нэгж)", "ru": "здание (счётное слово)"},
  {"ko": "진행되다", "en": "to be in process", "zh": "进行", "vi": "được tiến hành", "mn": "явагдах", "ru": "проводиться"},
  {"ko": "양반", "en": "aristocrat", "zh": "两班", "vi": "quý tộc", "mn": "язгууртан", "ru": "аристократ"},
  {"ko": "평상시", "en": "ordinary day", "zh": "平时", "vi": "ngày thường", "mn": "энгийн үе", "ru": "обычное время"},
  {"ko": "제사", "en": "ancestral rite", "zh": "祭祀", "vi": "lễ cúng", "mn": "тахилга", "ru": "поминальный обряд"},
  {"ko": "면", "en": "aspect", "zh": "方面", "vi": "phương diện", "mn": "тал", "ru": "аспект"},
  {"ko": "졸이다", "en": "to boil down", "zh": "熬煮", "vi": "kho (rim)", "mn": "өтгөрүүлэх", "ru": "уваривать"},
  {"ko": "매콤하다", "en": "to be spicy", "zh": "微辣", "vi": "cay cay", "mn": "халуун ногоотой", "ru": "островатый"},
  {"ko": "입맛을 당기다", "en": "to whet one’s appetite", "zh": "勾起食欲", "vi": "kích thích vị giác", "mn": "хоолны дуршил төрүүлэх", "ru": "возбуждать аппетит"},
  {"ko": "관광 안내도", "en": "tourist guide map", "zh": "旅游指南地图", "vi": "bản đồ hướng dẫn du lịch", "mn": "аялал жуулчлалын газрын зураг", "ru": "туристическая карта- путеводитель 서울대 한국어+ Student’s Book 4A 6  공연과 축제 Performances & Festivals 6-1    함께 즐기는 축제  Enjoying the Festival Together 한국어 표현 뜻 쪽"},
  {"ko": "행사에 참여하다", "en": "to take part in an event", "zh": "参加活动", "vi": "tham gia sự kiện", "mn": "арга хэмжээнд оролцох", "ru": "участвовать в мероприятии"},
  {"ko": "행사를 진행하다", "en": "to emcee an event", "zh": "主持活动", "vi": "dẫn chương trình", "mn": "арга хэмжээг хөтлөх", "ru": "вести мероприятие"},
  {"ko": "체험하다", "en": "to experience", "zh": "体验", "vi": "trải nghiệm", "mn": "биеэрээ туулах", "ru": "испытывать"},
  {"ko": "참가비를 내다", "en": "to pay a participation fee", "zh": "交纳参加费", "vi": "nộp phí tham gia", "mn": "оролцооны хураамж төлөх", "ru": "платить взнос за участие"},
  {"ko": "비용을 마련하다", "en": "to come up with the expenses", "zh": "筹措费用", "vi": "chuẩn bị chi phí", "mn": "зардал гаргах", "ru": "подготовить / собрать деньги (на что-то)"},
  {"ko": "장소를 찾다", "en": "to find a venue", "zh": "寻找场所", "vi": "tìm địa điểm", "mn": "газар хайх", "ru": "искать место"},
  {"ko": "일정을 정하다", "en": "to determine the schedule", "zh": "制定日程", "vi": "xác định lịch trình", "mn": "хуваарь гаргах", "ru": "определять расписание"},
  {"ko": "날씨를 고려하다", "en": "to take the weather into consideration", "zh": "考虑天气", "vi": "xem xét thời tiết", "mn": "цаг агаарыг харгалзах", "ru": "учитывать погоду"},
  {"ko": "구경거리 / 볼거리", "en": "attraction / spectacle", "zh": "看点", "vi": "điểm tham quan", "mn": "үзвэр", "ru": "достопримечательность"},
  {"ko": "일거리", "en": "things to do", "zh": "活儿", "vi": "việc làm", "mn": "ажил", "ru": "работа"},
  {"ko": "먹을거리", "en": "things to eat", "zh": "吃的东西", "vi": "đồ ăn", "mn": "идэх зүйл", "ru": "еда"},
  {"ko": "걱정거리", "en": "things to worry about", "zh": "烦心事", "vi": "chuyện lo lắng", "mn": "санаа зовох зүйл", "ru": "повод для беспокойства"},
  {"ko": "관심거리", "en": "things of interest", "zh": "感兴趣的事", "vi": "điều quan tâm", "mn": "сонирхолтой зүйл", "ru": "предмет интереса"},
  {"ko": "이야깃거리", "en": "things to talk about", "zh": "话题", "vi": "chủ đề nói chuyện", "mn": "ярих зүйл", "ru": "тема для разговора"},
  {"ko": "전달하다", "en": "to relay", "zh": "传达", "vi": "truyền đạt", "mn": "дамжуулах", "ru": "передавать"},
  {"ko": "즐길 거리", "en": "things to have fun", "zh": "玩的东西", "vi": "trò giải trí", "mn": "зугаацах зүйл", "ru": "развлечение"},
  {"ko": "스탠드", "en": "desk lamp", "zh": "台灯", "vi": "đèn bàn học", "mn": "ширээний гэрэл", "ru": "настольная лампа"},
  {"ko": "모국어", "en": "mother tongue", "zh": "母语", "vi": "tiếng mẹ đẻ", "mn": "эх хэл", "ru": "родной язык"},
  {"ko": "선발하다", "en": "to pick", "zh": "选拔", "vi": "tuyển chọn", "mn": "сонгон шалгаруулах", "ru": "отбирать"},
  {"ko": "도우미", "en": "helper", "zh": "帮手", "vi": "người giúp đỡ", "mn": "туслах", "ru": "помощник"},
  {"ko": "빈칸", "en": "blank", "zh": "空格", "vi": "chỗ trống", "mn": "хоосон нүд", "ru": "пробел"},
  {"ko": "자격", "en": "qualification", "zh": "资格", "vi": "tư cách", "mn": "эрх", "ru": "квалификация"},
  {"ko": "국적", "en": "nationality", "zh": "国籍", "vi": "quốc tịch", "mn": "иргэншил", "ru": "гражданство"},
  {"ko": "혜택", "en": "benefit", "zh": "优惠", "vi": "ưu đãi", "mn": "хөнгөлөлт", "ru": "льгота"},
  {"ko": "본인", "en": "me / you / own / oneself", "zh": "本人", "vi": "bản thân", "mn": "өөрөө", "ru": "сам (человек)"},
  {"ko": "제안하다", "en": "to suggest", "zh": "建议", "vi": "đề nghị", "mn": "санал болгох", "ru": "предлагать"},
  {"ko": "뽑히다", "en": "to be selected", "zh": "被选中", "vi": "được chọn", "mn": "сонгогдох", "ru": "быть выбранным"},
  {"ko": "찬성", "en": "approval", "zh": "赞成", "vi": "tán thành", "mn": "дэмжих", "ru": "одобрение"},
  {"ko": "마감일", "en": "deadline", "zh": "截止日期", "vi": "hạn chót", "mn": "эцсийн хугацаа", "ru": "крайний срок"},
  {"ko": "샐러드", "en": "salad", "zh": "沙拉", "vi": "salad", "mn": "салат", "ru": "салат"},
  {"ko": "퓨전", "en": "fusion", "zh": "融合", "vi": "kết hợp (fusion)", "mn": "холимог", "ru": "фьюжн"},
  {"ko": "감동적이다", "en": "to be moving", "zh": "感人", "vi": "tính cảm động", "mn": "сэтгэл хөдөлгөм", "ru": "трогательный"},
  {"ko": "수준이 높다 / 낮다", "en": "standard is high / low", "zh": "水平高 / 低", "vi": "trình độ cao / thấp", "mn": "түвшин өндөр / доогуур", "ru": "высокий / низкий уровень"},
  {"ko": "내용이 뻔하다", "en": "content is obvious", "zh": "内容老套", "vi": "nôi dung quá quen thuộc, nội dung quá dễ đoán, không có gì mới mẻ và bất ngờ", "mn": "агуулга нь ойлгомжтой", "ru": "содержание банально"},
  {"ko": "기대만 못하다", "en": "to not meet expectations", "zh": "不及预期", "vi": "không được như mong đợi", "mn": "хүлээлтэд хүрэхгүй", "ru": "не оправдать ожиданий"},
  {"ko": "연출이 뛰어나다", "en": "directing is outstanding", "zh": "导演手法出色", "vi": "đạo diễn xuất sắc", "mn": "найруулга сайн", "ru": "выдающаяся режиссура"},
  {"ko": "내용이 신선하다", "en": "content is fresh", "zh": "内容新颖", "vi": "nội dung mới mẻ", "mn": "агуулга шинэлэг", "ru": "свежее содержание"},
  {"ko": "연기가 형편없다", "en": "acting is terrible", "zh": "演技差劲", "vi": "diễn xuất tệ", "mn": "жүжиглэлт муу", "ru": "ужасная актерская игра"},
  {"ko": "좋은 반응을 얻다", "en": "to receive a good response", "zh": "获得良好反响", "vi": "nhận được phản hồi tốt", "mn": "сайн үнэлгээ авах", "ru": "получить хороший отклик"},
  {"ko": "목표를 이루다", "en": "to achieve a goal", "zh": "实现目标", "vi": "đạt được mục tiêu", "mn": "зорилгодоо хүрэх", "ru": "достигать цели"},
  {"ko": "의미가 있다", "en": "to be meaningful", "zh": "有意义", "vi": "có ý nghĩa", "mn": "утга учиртай", "ru": "иметь значение"},
  {"ko": "한계가 있다", "en": "to have a limit", "zh": "有局限性", "vi": "có giới hạn", "mn": "хязгаартай", "ru": "иметь предел"},
  {"ko": "홍보가 잘되다 / 안되다", "en": "to be highly promoted / to not be highly promoted", "zh": "宣传得好 / 不好", "vi": "được quảng bá tốt / không tốt", "mn": "сурталчилгаа сайн / муу явагдах", "ru": "хорошо / плохо разрекламирован"},
  {"ko": "매진", "en": "sold out", "zh": "售罄", "vi": "bán hết vé", "mn": "тасалбар дуусах", "ru": "всё продано"},
  {"ko": "개막하다", "en": "to open", "zh": "开幕", "vi": "khai mạc", "mn": "нээлтээ хийх", "ru": "открываться (о фестивале, выставке, соревновании)"},
  {"ko": "출연", "en": "cast", "zh": "出演", "vi": "diễn viên", "mn": "дүр", "ru": "актёрский состав"},
  {"ko": "역(할)", "en": "role", "zh": "角色", "vi": "vai diễn", "mn": "дүр", "ru": "роль"},
  {"ko": "순간", "en": "moment", "zh": "瞬间", "vi": "khoảnh khắc", "mn": "агшин", "ru": "момент"},
  {"ko": "선보이다", "en": "to offer", "zh": "展示", "vi": "ra mắt", "mn": "танилцуулах", "ru": "представлять"},
  {"ko": "현장", "en": "on-site", "zh": "现场", "vi": "hiện trường", "mn": "газар дээр нь", "ru": "на месте"},
  {"ko": "주재원", "en": "expatriate employee", "zh": "派驻人员", "vi": "nhân viên biệt phái", "mn": "томилолтын ажилтан", "ru": "командированный сотрудник"},
  {"ko": "자국", "en": "one’s own country", "zh": "本国", "vi": "nước mình", "mn": "эх орон", "ru": "своя страна"},
  {"ko": "장식품", "en": "ornament", "zh": "装饰品", "vi": "đồ trang trí", "mn": "гоёл чимэглэлийн зүйл", "ru": "украшение"},
  {"ko": "보완하다", "en": "to make up", "zh": "弥补", "vi": "bổ sung", "mn": "нөхөх", "ru": "дополнять"},
  {"ko": "구체적", "en": "detailed", "zh": "具体的", "vi": "cụ thể", "mn": "тодорхой", "ru": "конкретный"},
  {"ko": "인원", "en": "number of people", "zh": "人员", "vi": "số người", "mn": "хүний тоо", "ru": "количество человек"},
  {"ko": "대상", "en": "subject", "zh": "对象", "vi": "đối tượng", "mn": "хамрагдах хүн", "ru": "объект"},
  {"ko": "조사하다", "en": "to survey", "zh": "调查", "vi": "khảo sát", "mn": "судалгаа хийх", "ru": "исследовать"},
  {"ko": "차지하다", "en": "to account for", "zh": "占据", "vi": "chiếm", "mn": "эзлэх", "ru": "занимать (местро, позицию) 서울대 한국어+ Student’s Book 4A 7  숫자로 보는 세상 World in Numbers 7-1    조사 결과  Survey Results 한국어 표현 뜻 쪽"},
  {"ko": "순", "en": "order", "zh": "顺序", "vi": "thứ tự", "mn": "дараалал", "ru": "порядок"},
  {"ko": "나타나다", "en": "to show up", "zh": "出现", "vi": "xuất hiện", "mn": "илрэх", "ru": "появляться"},
  {"ko": "과반수", "en": "majority", "zh": "过半数", "vi": "đa số", "mn": "олонх", "ru": "большинство"},
  {"ko": "미만", "en": "under / below", "zh": "未满", "vi": "dưới", "mn": "хүрэхгүй", "ru": "менее чем (не включая)"},
  {"ko": "이상", "en": "and over", "zh": "以上", "vi": "trên", "mn": "дээш", "ru": "более"},
  {"ko": "이하", "en": "and below", "zh": "以下", "vi": "dưới", "mn": "доош", "ru": "не более чем... (включительно)"},
  {"ko": "절반 / 삼분의 일", "en": "half / 1/3 one third", "zh": "一半 / 三分之一", "vi": "một nửa / một phần ba", "mn": "хагас / гурвын нэг", "ru": "половина / одна треть"},
  {"ko": "연령", "en": "age", "zh": "年龄", "vi": "độ tuổi", "mn": "нас", "ru": "возраст"},
  {"ko": "출처", "en": "source", "zh": "出处", "vi": "nguồn", "mn": "эх сурвалж", "ru": "источник (информации, цитаты)"},
  {"ko": "밝히다", "en": "to reveal", "zh": "揭示", "vi": "tiết lộ", "mn": "илчлэх", "ru": "раскрывать"},
  {"ko": "청소년", "en": "teenager", "zh": "青少年", "vi": "thanh thiếu niên", "mn": "өсвөр насныхан", "ru": "подросток"},
  {"ko": "평균", "en": "average", "zh": "平均", "vi": "trung bình", "mn": "дундаж", "ru": "средний"},
  {"ko": "암", "en": "cancer", "zh": "癌症", "vi": "ung thư", "mn": "хорт хавдар", "ru": "рак (болезнь)"},
  {"ko": "정부", "en": "government", "zh": "政府", "vi": "chính phủ", "mn": "засгийн газар", "ru": "правительство"},
  {"ko": "예정", "en": "plan", "zh": "预定", "vi": "dự định", "mn": "төлөвлөгөө", "ru": "план"},
  {"ko": "길거리", "en": "street", "zh": "街头", "vi": "đường phố", "mn": "гудамж", "ru": "улица"},
  {"ko": "겨울철", "en": "wintertime", "zh": "冬季", "vi": "mùa đông", "mn": "өвлийн улирал", "ru": "зимний сезон"},
  {"ko": "시청", "en": "watching", "zh": "收看", "vi": "xem", "mn": "үзэх", "ru": "просмотр"},
  {"ko": "활용하다", "en": "to utilize", "zh": "利用", "vi": "tận dụng", "mn": "ашиглах", "ru": "использовать"},
  {"ko": "소비", "en": "consume", "zh": "消费", "vi": "tiêu thụ", "mn": "хэрэглээ", "ru": "потребление"},
  {"ko": "의류", "en": "clothing", "zh": "服装", "vi": "quần áo", "mn": "хувцас", "ru": "одежда"},
  {"ko": "경향", "en": "tendency", "zh": "倾向", "vi": "xu hướng", "mn": "хандлага", "ru": "тенденция"},
  {"ko": "연구소", "en": "research institute", "zh": "研究所", "vi": "viện nghiên cứu", "mn": "судалгааны хүрээлэн", "ru": "исследовательский институт"},
  {"ko": "각각", "en": "each", "zh": "各自", "vi": "mỗi", "mn": "тус бүр", "ru": "каждый"},
  {"ko": "만족감", "en": "satisfaction", "zh": "满足感", "vi": "cảm giác thỏa mãn", "mn": "сэтгэл ханамж", "ru": "удовлетворение"},
  {"ko": "분석하다", "en": "to analyze", "zh": "分析", "vi": "phân tích", "mn": "дүн шинжилгээ хийх", "ru": "анализировать"},
  {"ko": "통계청", "en": "Statistics Korea", "zh": "统计局", "vi": "cục thống kê", "mn": "статистикийн газар", "ru": "Статистическое управление (госорган)"},
  {"ko": "상반기", "en": "first half of the year", "zh": "上半年", "vi": "nửa đầu năm", "mn": "эхний хагас жил", "ru": "первое полугодие"},
  {"ko": "끼니", "en": "meal", "zh": "餐", "vi": "bữa ăn", "mn": "хоол", "ru": "приём пищи 7-2    통계와 그래프  Statistics & Graphs 한국어 표현 뜻 쪽"},
  {"ko": "늘어나다", "en": "to grow", "zh": "增加", "vi": "tăng lên", "mn": "нэмэгдэх", "ru": "расти"},
  {"ko": "오르다", "en": "to go up", "zh": "上涨", "vi": "tăng", "mn": "өсөх", "ru": "подниматься"},
  {"ko": "인상하다", "en": "to raise", "zh": "提高", "vi": "tăng", "mn": "нэмэгдүүлэх", "ru": "повышать"},
  {"ko": "늘리다", "en": "to expand", "zh": "增加", "vi": "mở rộng", "mn": "нэмэгдүүлэх", "ru": "расширять"},
  {"ko": "줄어들다", "en": "to shrink", "zh": "减少", "vi": "giảm đi", "mn": "багасах", "ru": "сокращаться"},
  {"ko": "감소하다", "en": "to decrease", "zh": "减少", "vi": "giảm", "mn": "буурах", "ru": "уменьшаться"},
  {"ko": "내리다", "en": "to bring down", "zh": "下降", "vi": "giảm", "mn": "бууруулах", "ru": "снижать"},
  {"ko": "인하하다", "en": "to lower", "zh": "降低", "vi": "hạ", "mn": "бууруулах", "ru": "понижать"},
  {"ko": "줄이다", "en": "to reduce", "zh": "减少", "vi": "giảm bớt", "mn": "багасгах", "ru": "сокращать"},
  {"ko": "경쟁률", "en": "competition rate", "zh": "竞争率", "vi": "tỷ lệ cạnh tranh", "mn": "өрсөлдөөний түвшин", "ru": "уровень конкуренции"},
  {"ko": "비율", "en": "ratio", "zh": "比率", "vi": "tỷ lệ", "mn": "харьцаа", "ru": "соотношение"},
  {"ko": "취업률", "en": "employment rate", "zh": "就业率", "vi": "tỷ lệ việc làm", "mn": "ажил эрхлэлтийн түвшин", "ru": "уровень занятости"},
  {"ko": "확률", "en": "probability", "zh": "概率", "vi": "xác suất", "mn": "магадлал", "ru": "вероятность"},
  {"ko": "환율", "en": "exchange rate", "zh": "汇率", "vi": "tỷ giá hối đoái", "mn": "валютын ханш", "ru": "обменный курс"},
  {"ko": "1인당", "en": "per person", "zh": "人均", "vi": "mỗi người", "mn": "нэг хүнд ногдох", "ru": "на одного человека"},
  {"ko": "구매량", "en": "purchase quantity", "zh": "购买量", "vi": "lượng mua", "mn": "худалдан авалтын хэмжээ", "ru": "объём покупок"},
  {"ko": "문항", "en": "question", "zh": "问题项目", "vi": "hạng mục, câu hỏi", "mn": "асуулт", "ru": "пункт (вопроса)"},
  {"ko": "참고하다", "en": "to refer", "zh": "参考", "vi": "tham khảo", "mn": "лавлах", "ru": "ссылаться на / использовать как справку"},
  {"ko": "명확하다", "en": "to be clear", "zh": "明确", "vi": "rõ ràng", "mn": "тодорхой", "ru": "ясный"},
  {"ko": "답항", "en": "answer", "zh": "答案选项", "vi": "đáp án", "mn": "хариулт", "ru": "вариант ответа"},
  {"ko": "구성하다", "en": "to compose", "zh": "构成", "vi": "cấu thành", "mn": "бүрдүүлэх", "ru": "составлять"},
  {"ko": "응답자", "en": "respondent", "zh": "回答者", "vi": "người trả lời", "mn": "хариулагч", "ru": "респондент"},
  {"ko": "주관식", "en": "short-answer question", "zh": "主观题", "vi": "câu hỏi tự luận", "mn": "нээлттэй асуулт", "ru": "вопрос с открытым ответом"},
  {"ko": "연간", "en": "yearly", "zh": "年间", "vi": "hàng năm", "mn": "жилийн", "ru": "годовой"},
  {"ko": "점차", "en": "gradually", "zh": "逐渐", "vi": "dần dần", "mn": "аажмаар", "ru": "постепенно"},
  {"ko": "소비량", "en": "consumption amount", "zh": "消费量", "vi": "lượng tiêu thụ", "mn": "хэрэглээний хэмжээ", "ru": "объём потребления"},
  {"ko": "가공용", "en": "processing purpose", "zh": "加工用", "vi": "dùng để gia công", "mn": "боловсруулах зориулалттай", "ru": "предназначенный для промышленной обработки"},
  {"ko": "추세", "en": "trend", "zh": "趋势", "vi": "xu thế", "mn": "чиг хандлага", "ru": "тенденция"},
  {"ko": "접하다", "en": "to encounter", "zh": "接触", "vi": "tiếp xúc", "mn": "тулгарах", "ru": "сталкиваться"},
  {"ko": "다소", "en": "somewhat", "zh": "稍微", "vi": "ít nhiều", "mn": "бага зэрэг", "ru": "несколько"},
  {"ko": "이처럼", "en": "in this way", "zh": "如此", "vi": "như thế này", "mn": "ийм байдлаар", "ru": "таким образом 서울대 한국어+ Student’s Book 4A 8  대중문화 Pop Culture 8-1    스타와 대중문화  Stars & Pop Culture 한국어 표현 뜻 쪽"},
  {"ko": "꿈만 같다", "en": "to be like a dream", "zh": "如梦一般", "vi": "như một giấc mơ", "mn": "зүүд мэт", "ru": "как во сне"},
  {"ko": "믿기지 않다", "en": "to be unbelievable", "zh": "难以置信", "vi": "không thể tin được", "mn": "итгэмээргүй", "ru": "не верится"},
  {"ko": "숨이 멎다", "en": "to not be able to breathe", "zh": "窒息", "vi": "nghẹt thở", "mn": "амьсгал хураах", "ru": "дух захватывает 실감이 안 나다 /"},
  {"ko": "실감 나다", "en": "to not sink in / to sink in", "zh": "没有实感 / 有实感", "vi": "không cảm thấy thật / cảm thấy thật", "mn": "бодит мэт санагдахгүй / санагдах", "ru": "не ощущается как реальность / ощущается по-настоящему"},
  {"ko": "심장이 터질 것 같다", "en": "heart is about to burst", "zh": "心脏要爆炸了", "vi": "tim như muốn nổ tung", "mn": "зүрх дэлбэрэх гэж байна", "ru": "сердце готово выпрыгнуть"},
  {"ko": "수상하다", "en": "to be awarded", "zh": "获奖", "vi": "được trao giải", "mn": "шагнал авах", "ru": "быть награждённым"},
  {"ko": "인기를 끌다", "en": "to gain popularity", "zh": "受欢迎", "vi": "thu hút sự nổi tiếng", "mn": "алдартай болох", "ru": "завоевать популярность"},
  {"ko": "주목을 받다", "en": "to be in the limelight", "zh": "受到关注", "vi": "nhận được sự chú ý", "mn": "анхаарал татах", "ru": "привлекать внимание"},
  {"ko": "무대에 서다", "en": "to go on stage", "zh": "登上舞台", "vi": "đứng trên sân khấu", "mn": "тайзан дээр гарах", "ru": "выходить на сцену"},
  {"ko": "작품에 출연하다", "en": "to appear in a movie / drama", "zh": "出演作品", "vi": "xuất hiện trong tác phẩm", "mn": "бүтээлд тоглох", "ru": "сниматься в произведении"},
  {"ko": "역할을 맡다", "en": "to take on a role", "zh": "担任角色", "vi": "đảm nhận vai diễn", "mn": "дүр бүтээх", "ru": "исполнять роль"},
  {"ko": "팀을 옮기다", "en": "to change teams", "zh": "转队", "vi": "chuyển đội", "mn": "багаа солих", "ru": "сменить команду"},
  {"ko": "새 앨범을 내다", "en": "to release a new album", "zh": "发行新专辑", "vi": "phát hành album mới", "mn": "шинэ цомог гаргах", "ru": "выпустить новый альбом"},
  {"ko": "가능성", "en": "possibility", "zh": "可能性", "vi": "khả năng", "mn": "боломж", "ru": "возможность"},
  {"ko": "확신하다", "en": "to be certain", "zh": "确信", "vi": "chắc chắn", "mn": "итгэлтэй байх", "ru": "быть уверенным"},
  {"ko": "실물", "en": "in person", "zh": "实物", "vi": "người thật", "mn": "бодит байдал", "ru": "реальный объект"},
  {"ko": "공개하다", "en": "to be dropped", "zh": "公开", "vi": "công khai", "mn": "нийтэд дэлгэх", "ru": "раскрывать"},
  {"ko": "긴장하다", "en": "to be nervous", "zh": "紧张", "vi": "căng thẳng", "mn": "сандрах", "ru": "нервничать"},
  {"ko": "쪽지", "en": "note", "zh": "纸条", "vi": "mẩu giấy", "mn": "зурвас", "ru": "записка"},
  {"ko": "악수하다", "en": "to shake hands", "zh": "握手", "vi": "bắt tay", "mn": "гар барих", "ru": "пожимать руку"},
  {"ko": "예전", "en": "former", "zh": "以前", "vi": "trước đây", "mn": "өмнө", "ru": "прошлое"},
  {"ko": "은퇴하다", "en": "to retire", "zh": "退休", "vi": "nghỉ hưu", "mn": "тэтгэвэрт гарах", "ru": "уходить на пенсию"},
  {"ko": "근황", "en": "current situation", "zh": "近况", "vi": "tình hình gần đây", "mn": "сүүлийн үеийн байдал", "ru": "текущая ситуация"},
  {"ko": "부문", "en": "category", "zh": "部门", "vi": "phần, lĩnh vực, môn", "mn": "ангилал", "ru": "категория / сфера / отдел"},
  {"ko": "원작", "en": "original work", "zh": "原作", "vi": "tác phẩm gốc", "mn": "эх зохиол", "ru": "оригинал (произведение)"},
  {"ko": "꼽히다", "en": "to be in ranking", "zh": "被选为", "vi": "được xem là", "mn": "тооцогдох", "ru": "считаться"},
  {"ko": "여우주연상", "en": "best actress award", "zh": "最佳女主角奖", "vi": "giải nữ diễn viên chính xuất sắc nhất", "mn": "шилдэг эмэгтэй жүжигчний шагнал", "ru": "премия за лучшую женскую роль"},
  {"ko": "입소문을 타다", "en": "to spread through word of mouth", "zh": "口碑相传", "vi": "được truyền miệng", "mn": "ам дамжин яригдах", "ru": "распространяться по слухам"},
  {"ko": "관계자", "en": "official", "zh": "相关人员", "vi": "người có liên quan", "mn": "холбогдох этгээд", "ru": "официальное лицо"},
  {"ko": "다수", "en": "majority", "zh": "多数", "vi": "đa số", "mn": "олонх", "ru": "большинство"},
  {"ko": "예상을 깨다", "en": "to break expectations", "zh": "打破预想", "vi": "phá vỡ dự đoán", "mn": "таамгийг эвдэх", "ru": "превзойти ожидания"},
  {"ko": "의상", "en": "costume", "zh": "服装", "vi": "trang phục", "mn": "хувцас", "ru": "костюм"},
  {"ko": "후보", "en": "candidate", "zh": "候选人", "vi": "ứng cử viên", "mn": "нэр дэвшигч", "ru": "кандидат"},
  {"ko": "워낙", "en": "so", "zh": "本来就", "vi": "vốn dĩ", "mn": "үнэхээр", "ru": "настолько"},
  {"ko": "몸 둘 바를 모르다", "en": "to not know how to react", "zh": "不知所措", "vi": "không biết phải làm sao", "mn": "биеэ авч явахаа мэдэхгүй байх", "ru": "не знать, куда себя деть"},
  {"ko": "겸손하다", "en": "to be humble", "zh": "谦虚", "vi": "khiêm tốn", "mn": "даруухан", "ru": "быть скромным 8-2    대중문화의 영향  Pop Culture Influence 한국어 표현 뜻 쪽"},
  {"ko": "위로를 받다", "en": "to be comforted", "zh": "得到安慰", "vi": "được an ủi", "mn": "тайвшрал авах", "ru": "получать утешение"},
  {"ko": "용기를 얻다", "en": "to gain courage", "zh": "获得勇气", "vi": "có được dũng khí", "mn": "зориг авах", "ru": "набраться смелости"},
  {"ko": "즐거움을 얻다", "en": "to get pleasure", "zh": "获得乐趣", "vi": "có được niềm vui", "mn": "баяр баясгалан авах", "ru": "получать удовольствие"},
  {"ko": "영향력이 커지다", "en": "to become more influential", "zh": "影响力变大", "vi": "có tầm ảnh hưởng lớn", "mn": "нөлөө ихсэх", "ru": "влияние растёт"},
  {"ko": "관심을 끌다", "en": "to attract attention", "zh": "引起关注", "vi": "thu hút sự quan tâm", "mn": "анхаарал татах", "ru": "привлекать внимание"},
  {"ko": "유행을 이끌다", "en": "to lead trends", "zh": "引领潮流", "vi": "dẫn đầu xu hướng", "mn": "моодыг тэргүүлэх", "ru": "задавать тренд"},
  {"ko": "무소식", "en": "no news", "zh": "没消息", "vi": "không có tin tức", "mn": "сураггүй", "ru": "без новостей"},
  {"ko": "무조건", "en": "unconditionally", "zh": "无条件地", "vi": "vô điều kiện", "mn": "болзолгүй", "ru": "безоговорочно"},
  {"ko": "무관심하다", "en": "to be indifferent", "zh": "漠不关心", "vi": "thờ ơ", "mn": "хайхрамжгүй", "ru": "быть безразличным"},
  {"ko": "무의미하다", "en": "to be meaningless", "zh": "毫无意义", "vi": "vô nghĩa", "mn": "утгагүй", "ru": "бессмысленный"},
  {"ko": "무책임하다", "en": "to be irresponsible", "zh": "不负责任", "vi": "vô trách nhiệm", "mn": "хариуцлагагүй", "ru": "безответственный"},
  {"ko": "댓글", "en": "comment", "zh": "评论", "vi": "bình luận", "mn": "сэтгэгдэл", "ru": "комментарий"},
  {"ko": "화환", "en": "wreath", "zh": "花环", "vi": "vòng hoa", "mn": "цэцгэн хэлхээ", "ru": "венок"},
  {"ko": "포즈를 취하다", "en": "to strike a pose", "zh": "摆姿势", "vi": "tạo dáng", "mn": "зураг авахуулах", "ru": "позировать"},
  {"ko": "낭비", "en": "waste", "zh": "浪费", "vi": "lãng phí", "mn": "үрэлгэн байдал", "ru": "пустая трата"},
  {"ko": "이미지", "en": "image", "zh": "形象", "vi": "hình ảnh", "mn": "дүр төрх", "ru": "имидж"},
  {"ko": "성과", "en": "outcome", "zh": "成果", "vi": "thành quả", "mn": "үр дүн", "ru": "результат"},
  {"ko": "꼬리표", "en": "tag", "zh": "标签", "vi": "nhãn mác", "mn": "шошго", "ru": "ярлык"},
  {"ko": "당시", "en": "at that time", "zh": "当时", "vi": "lúc đó", "mn": "тэр үед", "ru": "в то время"},
  {"ko": "실감하다", "en": "to actually feel", "zh": "实际感受到", "vi": "cảm nhận thực tế, cảm nhận như thật", "mn": "бодитоор мэдрэх", "ru": "реально ощущать"},
  {"ko": "기존", "en": "existing", "zh": "现有", "vi": "vốn có, sẵn có", "mn": "одоо байгаа", "ru": "существующий"},
  {"ko": "발전적이다", "en": "to be developmental", "zh": "发展的", "vi": "có tính phát triển", "mn": "хөгжилтэй", "ru": "прогрессивный 서울대 한국어+ Student’s Book 4A 9  스포츠의 세계 World of Sports 9-1    흥미진진한 경기  Exciting Matches 한국어 표현 뜻 쪽"},
  {"ko": "승부가 나다", "en": "win and loss is determined", "zh": "分出胜负", "vi": "phân thắng bại", "mn": "ялалт ялагдал тодрох", "ru": "исход решён"},
  {"ko": "비기다", "en": "to tie", "zh": "打平", "vi": "hòa", "mn": "тэнцэх", "ru": "сыграть вничью"},
  {"ko": "무승부로 끝나다", "en": "to end in a draw", "zh": "以平局结束", "vi": "kết thúc với tỷ số hòa", "mn": "тэнцээгээр өндөрлөх", "ru": "закончиться вничью"},
  {"ko": "역전하다", "en": "to win from behind", "zh": "逆转", "vi": "lội ngược dòng", "mn": "эргүүлэн ялах", "ru": "вырваться вперёд"},
  {"ko": "연장전을 하다", "en": "to go into overtime", "zh": "进行加时赛", "vi": "thi đấu hiệp phụ", "mn": "нэмэлт цаг авах", "ru": "играть дополнительное время"},
  {"ko": "결승전에 진출하다", "en": "to make it to the finals", "zh": "进入决赛", "vi": "vào vòng chung kết", "mn": "шигшээ тоглолтод шалгарах", "ru": "выйти в финал"},
  {"ko": "예선에서 탈락하다", "en": "to be eliminated", "zh": "在预选赛中被淘汰", "vi": "bị loại ở vòng sơ loại", "mn": "урьдчилсан шатнаас хасагдах", "ru": "выбыть в отборочном туре"},
  {"ko": "정정당당하다", "en": "to be fair and square", "zh": "堂堂正正", "vi": "công bằng, chính trực", "mn": "шударгаар", "ru": "честный и справедливый (о соревновании)"},
  {"ko": "아슬아슬하다", "en": "to be a close call", "zh": "惊险", "vi": "gay cấn", "mn": "ана мана үзэх", "ru": "на волоске"},
  {"ko": "흥미진진하다", "en": "to be exciting", "zh": "津津有味", "vi": "hấp dẫn", "mn": "сонирхолтой", "ru": "захватывающий"},
  {"ko": "우왕좌왕하다", "en": "to move in confusion", "zh": "彷徨", "vi": "hỗn loạn", "mn": "нааш цааш холхих", "ru": "метаться в замешательстве"},
  {"ko": "고만고만하다", "en": "to be almost the same", "zh": "差不多", "vi": "tương đương, không chênh lệch nhiều", "mn": "ойролцоо", "ru": "примерно одинаковый (об уровне)"},
  {"ko": "내기", "en": "bet", "zh": "打赌", "vi": "sự cá cược", "mn": "мөрий", "ru": "пари"},
  {"ko": "시합", "en": "match", "zh": "比赛", "vi": "việc thi đấu, việc so tài", "mn": "тэмцээн", "ru": "матч"},
  {"ko": "간신히", "en": "barely", "zh": "勉强", "vi": "vừa đủ", "mn": "арай гэж", "ru": "едва"},
  {"ko": "부상을 당하다", "en": "to be injured", "zh": "受伤", "vi": "bị thương", "mn": "гэмтэх", "ru": "получить травму"},
  {"ko": "뺏기다", "en": "to be intercepted", "zh": "被抢走", "vi": "bị cướp", "mn": "булаалгах", "ru": "быть отобранным"},
  {"ko": "골대", "en": "goalpost", "zh": "球门", "vi": "cột gôn", "mn": "гоал", "ru": "ворота"},
  {"ko": "연속으로", "en": "consecutively", "zh": "连续", "vi": "liên tiếp", "mn": "дарааллан", "ru": "подряд"},
  {"ko": "골을 넣다", "en": "to score a goal", "zh": "进球", "vi": "ghi bàn", "mn": "гоол оруулах", "ru": "забивать гол"},
  {"ko": "중계", "en": "broadcast", "zh": "转播", "vi": "truyền hình trực tiếp", "mn": "дамжуулалт", "ru": "трансляция"},
  {"ko": "후반전", "en": "second half", "zh": "下半场", "vi": "hiệp hai", "mn": "хоёрдугаар үе", "ru": "второй тайм"},
  {"ko": "체력이 떨어지다", "en": "lose strength", "zh": "体力下降", "vi": "thể lực suy giảm", "mn": "тамир тэнхээ муудах", "ru": "силы иссякают"},
  {"ko": "결정적이다", "en": "to be crucial", "zh": "决定性的", "vi": "mang tính quyết định", "mn": "шийдвэрлэх", "ru": "решающий"},
  {"ko": "8강", "en": "quarterfinals", "zh": "八强", "vi": "tứ kết", "mn": "шилдэг найм", "ru": "четвертьфинал"},
  {"ko": "출전하다", "en": "to participate in", "zh": "出战", "vi": "tham chiến", "mn": "оролцох", "ru": "участвовать (в соревновании)"},
  {"ko": "해설을 맡다", "en": "to be in charge of commentary", "zh": "担任解说", "vi": "phụ trách bình luận", "mn": "тайлбарлах", "ru": "комментировать"},
  {"ko": "부담감", "en": "burden", "zh": "负担感", "vi": "gánh nặng, áp lực", "mn": "дарамт", "ru": "бремя"},
  {"ko": "발휘하다", "en": "to display", "zh": "发挥", "vi": "phát huy", "mn": "гаргах", "ru": "проявлять"},
  {"ko": "종료", "en": "end", "zh": "结束", "vi": "kết thúc", "mn": "дуусах", "ru": "окончание"},
  {"ko": "차분하다", "en": "to be calm", "zh": "沉着", "vi": "điềm tĩnh", "mn": "тайван", "ru": "спокойный"},
  {"ko": "각오", "en": "determination", "zh": "决心", "vi": "sự quyết tâm", "mn": "шийдвэр", "ru": "решимость"},
  {"ko": "만약", "en": "if", "zh": "万一", "vi": "nếu", "mn": "хэрэв", "ru": "если"},
  {"ko": "맞붙다", "en": "to play against", "zh": "对阵", "vi": "đối đầu", "mn": "өрсөлдөх", "ru": "состязаться 9-2    경기와 규칙  Matches & Rules 한국어 표현 뜻 쪽"},
  {"ko": "득점하다", "en": "to score a point", "zh": "得分", "vi": "ghi điểm", "mn": "оноо авах", "ru": "набирать очки"},
  {"ko": "실점하다", "en": "to lose a point", "zh": "失分", "vi": "mất điểm", "mn": "оноо алдах", "ru": "терять очки"},
  {"ko": "공격하다", "en": "to play offense", "zh": "攻击", "vi": "tấn công", "mn": "довтлох", "ru": "атаковать"},
  {"ko": "공격을 막다 / 수비하다", "en": "to play defense / to defend", "zh": "防守", "vi": "phòng thủ", "mn": "хамгаалах", "ru": "защищаться / отражать атаку"},
  {"ko": "기록을 측정하다", "en": "to measure a record", "zh": "测量记录", "vi": "đo lường kỷ lục", "mn": "амжилтыг хэмжих", "ru": "измерять рекорд"},
  {"ko": "기록을 비교하다", "en": "to compare records", "zh": "比较记录", "vi": "so sánh kỷ lục", "mn": "амжилтыг харьцуулах", "ru": "сравнивать рекорды"},
  {"ko": "점수를 매기다", "en": "to give marks", "zh": "打分", "vi": "chấm điểm", "mn": "оноо тавих", "ru": "считать очки"},
  {"ko": "규칙을 지키다", "en": "to obey the rules", "zh": "遵守规则", "vi": "tuân thủ quy tắc", "mn": "дүрэм сахих", "ru": "соблюдать правила"},
  {"ko": "반칙을 하다", "en": "to make a foul", "zh": "犯规", "vi": "phạm lỗi", "mn": "булхайцах", "ru": "нарушать правила"},
  {"ko": "경고를 받다 / 주다", "en": "to receive / give a warning", "zh": "受到 / 给予警告", "vi": "nhận / đưa ra cảnh cáo", "mn": "сануулга авах / өгөх", "ru": "получать / давать предупреждение"},
  {"ko": "퇴장을 당하다", "en": "to be ejected", "zh": "被罚下场", "vi": "bị đuổi khỏi sân", "mn": "талбайгаас хөөгдөх", "ru": "быть удалённым с поля"},
  {"ko": "선을 밟다", "en": "to step on the line", "zh": "踩线", "vi": "giẫm lên vạch", "mn": "зураасан дээр гишгэх", "ru": "наступать на линию"},
  {"ko": "그물(네트)에 닿다", "en": "to touch the net", "zh": "触网", "vi": "chạm lưới", "mn": "торонд хүрэх", "ru": "касаться сетки"},
  {"ko": "무술", "en": "martial arts", "zh": "武术", "vi": "võ thuật", "mn": "тулааны урлаг", "ru": "боевое искусство"},
  {"ko": "택견", "en": "traditional Korean martial arts", "zh": "跆跟", "vi": "Taekkyeon", "mn": "тэггён", "ru": "тхэккён (традиционное корейское боевое искусство)"},
  {"ko": "세계인", "en": "people around the world", "zh": "全世界的人", "vi": "người dân thế giới", "mn": "дэлхийн хүмүүс", "ru": "люди всего мира"},
  {"ko": "형식", "en": "form", "zh": "形式", "vi": "hình thức", "mn": "хэлбэр", "ru": "форма"},
  {"ko": "정식", "en": "official", "zh": "正式", "vi": "chính thức", "mn": "албан ёсны", "ru": "официальный"},
  {"ko": "성장", "en": "growth", "zh": "成长", "vi": "sự trưởng thành", "mn": "өсөлт", "ru": "рост"},
  {"ko": "강화", "en": "strengthening", "zh": "强化", "vi": "tăng cường", "mn": "бэхжүүлэх", "ru": "укрепление"},
  {"ko": "해소", "en": "relief", "zh": "消除", "vi": "giải tỏa", "mn": "тайлах", "ru": "снятие"},
  {"ko": "겨루기", "en": "sparring", "zh": "搏击", "vi": "so tài, đấu nhau để phân thắng bại", "mn": "тулаан", "ru": "спарринг"},
  {"ko": "품새", "en": "form", "zh": "品势", "vi": "bài quyền", "mn": "чанартай", "ru": "пхумсэ (формальные упражнения в тхэквондо)"},
  {"ko": "회전", "en": "round", "zh": "回合", "vi": "quay vòng", "mn": "үе", "ru": "раунд"},
  {"ko": "쥐다", "en": "to grab", "zh": "握", "vi": "nắm", "mn": "атгах", "ru": "сжимать"},
  {"ko": "몸통", "en": "torso", "zh": "躯干", "vi": "phần thân", "mn": "их бие", "ru": "туловище"},
  {"ko": "강조하다", "en": "to emphasize", "zh": "强调", "vi": "nhấn mạnh", "mn": "онцлох", "ru": "акцентировать, подчеркивать"}
]);